### ISSUE TITLE
Can't find Data

### ISSUE THREAD

**Issue by Saylance** [ladislav-zezula/CascLib#10]
Hi.
Here is some problem with Russian client.
http://s016.radikal.ru/i335/1411/14/fb2516988e80.jpg
It cant open storage, but PATH is true.

CASCViewer ver. 1.0.0.7
The same problem with Beta client, and MAP Extractor in Trinity Core 6.x

**Comment by ladislav-zezula** [comment]
Does CascView v 1.0.0.12 still have that error?

**Comment by Saylance** [comment]
Now work.
Close.
