### ISSUE TITLE
Fewer unknown files in latest build

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#105]
I downloaded the latest version of CascView and noticed that the number of unknown files had dropped a lot over the version I'd been using previously. There's a number of .blp images that we don't know the names for yet and some are now missing, despite the fact we still haven't guessed their names.

I guess this happened around the same time you renamed the unknown folder from "unknown" to  "CONTENT_KEY"?

Is there somewhere I can download an older version of CascView in the meantime? I overwrote the one i had.

Thanks!

**Comment by ladislav-zezula** [comment]
I'll check, but generally, new version of CascLib considers the file uniqueness (when searching the archive fr unknown files) by their Encoded Key. Those are guaranteed to be in the archive.

The name of the folder "CONTENT_KEY" comes from the fact that what you see in the file name is the content key, a.k.a. MD5 of the file.

**Comment by ladislav-zezula** [comment]
Here older build: http://www.zezula.net/download/cascview_old.zip

**Comment by WainPetopia** [comment]
Actually, I was going to suggest that you could link this Github repository instead of hosting the listfile:
https://github.com/wowdev/wow-listfile
It's kept up to date and is the one I rely on :)

**Comment by WainPetopia** [comment]
Thanks for the link. I'll compare the number of files each one pulls.

**Comment by WainPetopia** [comment]
OK, using the same WoW beta build and the same listfile, the old version of CascView finds 2936 unknowns. The new version finds 816. So it's missing 2120 unknown files.

All of the files found by the new version are found by the old one. I'm attaching a list of all the files it missed in the current build (26788 ).

[unknownsDiff.txt](https://github.com/ladislav-zezula/CascLib/files/2086570/unknownsDiff.txt)

**Comment by ladislav-zezula** [comment]
I checked what you said and you actually discovered a bug in CascLib. A good 1/3 of the unknown files were indeed missing. I fixed that bug, made a new CascLib release.

I made a new release of CascView as well and I carefully checked the new build with the old one. The files counts in `CONTENT_KEY` now match to what was `unknowns` before.

You can now stop using the old version, use the new one. Should be OK now.
Thanks for discovering the bug and for the listfile.

**Comment by WainPetopia** [comment]
Thanks very much for the quick fix! Your program is pretty much essential for our website work and datamining and I really appreciate all the work you put into it. :)

If I could suggest a new feature - not essential but could be useful - it would be to be able to export a listfile of all files in the CascView tree. This could be useful for seeing which files were found (which may not be all of the ones in the listfile the user supplies, and may include unnamed files the user's listfile didn't cover).  Thanks :)

**Comment by ladislav-zezula** [comment]
Sure. Try this out and let me know if that's OK:
http://www.zezula.net/download/cascview_en_with_export.zip

**Comment by WainPetopia** [comment]
That seems to work, thanks :) It found just under 850k files for BfA.

A few suggestions, if you don't mind:
- maybe add a path prefix to the unidentified files? They currently have no path and if you sort the list the unidentified files will sort all over the place and not stay together.
- sort folders alphabetically? Not a huge deal since users can sort later. 
- UNIX clash paths are usually nicer, but again not a big deal.

Thanks again :)

**Comment by ladislav-zezula** [comment]
Ok, probly the best will be a short config dialog before writing the listfile. Check out the new build on my web: http://www.zezula.net/download/cascview_en.zip
