### ISSUE TITLE
WoW game folder is "corrupted and unreadable". 

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#107]
If I try to read the WoW live or Beta game databases with the latest CASCView I get the error:
"Failed to open game storage <path>. The file or directory is corrupted and unreadable."
It gives this error on both game versions and I've ensured that the Battle.net app is properly closed and no Agent processes are running. The game folders also open in WMV so they don't seem corrupted.

Are you seeing this error too?  I don't have an older version of CascView on hand to check if it's a problem with the latest version.

**Comment by ladislav-zezula** [comment]
Sorry for that. Fixed in the latest build.

**Comment by WainPetopia** [comment]
Thanks Ladislav! :)
