### ISSUE TITLE
Warcraft 3 support

### ISSUE THREAD

**Issue by stijnherfst** [ladislav-zezula/CascLib#109]
With the 1.30 update (now in PTR) Warcraft 3 has started using CASC storage for their game data files (map remain MPQs for now). Having support for opening Warcraft 3 game data would allow me to support 1.30 too.

**Comment by Marlamin** [comment]
With the TVFS stuff he's added recently it should theoretically already be supported?

**Comment by stijnherfst** [comment]
Currently you get an assert that the game data files aren't supported. If you change the CASC config file to one of the supported identifiers for, for instance WoW then it fails with error 2.

**Comment by Marlamin** [comment]
I was able to read the "virtual" MPQ files inside the data with casview, which I assume uses casclib so some of it is working atleast. Might need some additional tinkering, maybe?

**Comment by LiquidWater** [comment]
the war3 cascs opened for me without errors, but theres no listfile so it just shows hashes instead of filenames

**Comment by ladislav-zezula** [comment]
Guys, wait a little. The TVFS was indeed for the newly prepared version of Warcraft III. I only tested it on some simple TVFS examples. As soon as I test it on a real game, It'll be done.

**Comment by ladislav-zezula** [comment]
Fixed in commit c42326e03c0f357bf0e67a5931b76441a9428034.
Fixed in CascView version 1.0.2.75.
