### ISSUE TITLE
Loop index not used

### ISSUE THREAD

**Issue by sgraf812** [ladislav-zezula/CascLib#11]
Hi, 

while transcribing this, I recognized an unaccessed loop variable that most likely should be accessed:

https://github.com/ladislav-zezula/CascLib/blob/master/src/CascOpenStorage.cpp#L456-L465

Just thought I'd leave that here. I'm unsure what the correct fix is so no PR, sorry.

**Comment by ladislav-zezula** [comment]
The variable is being accessed in the loop?

**Comment by sgraf812** [comment]
`i` is not, if see this correctly. I fixed the line numbers btw, they were 10 lines off.

**Comment by ladislav-zezula** [comment]
Fixed: 99d9812be9128a67561af1e4f093c2aa0be7140f
Not verified, as none of my currently archived WoW storages utilises that branch of code
