### ISSUE TITLE
Redeclared symbols when using in unison with StormLib

### ISSUE THREAD

**Issue by stijnherfst** [ladislav-zezula/CascLib#111]
When using both StormLib and CascLib together in one project you get the following errors:
![image](https://user-images.githubusercontent.com/8471644/43857805-ab7417d8-9b4c-11e8-9359-6b609843ab6e.png)
Renaming those functions to something else solves the issue.

**Comment by ladislav-zezula** [comment]
Add /FORCE:MULTIPLE into linker command line options.

**Comment by ladislav-zezula** [comment]
I was thinking about renaming, but there is quite a lot of functions transferred from StormLib, which inevitably leads to duplicate symbols. So let's try with /FORCE:MULTIPLE, for now.

**Comment by stijnherfst** [comment]
Why not use namespaces? This is exactly what they are made for.

**Comment by herrvigg** [comment]
True, namespace should be the cleanest solution.
