### ISSUE TITLE
Doesn't extract everything

### ISSUE THREAD

**Issue by freekode** [ladislav-zezula/CascLib#12]
May be I am doing something wrong, but Casc Viewer does not opening everything which described in the list file. For example minimaps, there is no folder in the program, but files of Minimaps directory written in list file: `World\Minimaps\WMO\Dungeon\Azjol_Uppercity\Azjol_Uppercity_001_02_05.blp` 
During opening storage there are no errors.
CASC Viewer 1.0.0.11
WoW enUS 6.0.3.19342

**Comment by ladislav-zezula** [comment]
I'll look at it.

**Comment by ladislav-zezula** [comment]
I tried with WoW 6.0.3.19342 (enGB) and it works. Could you please re-check with enUS?

**Comment by spectras** [comment]
I don't know if it is related, but it seems for me using wildcards for globbing results in only all-caps files being extracted. If the filename has even one lowercase letter, it will be skipped.

Maybe I should open another issue?

**Comment by ladislav-zezula** [comment]
Happens in CascFindNextFile or in CascView?

**Comment by spectras** [comment]
I'm using https://github.com/Kanma/CASCExtractor I am not the author but it's a very simple wrapper around your lib and I should be able to understand and help trace things around.

From what I can tell, its main loop is lines 189-207, and uses `CascFindFirstFile`/`CascFindNextFile`

**Comment by Kanma** [comment]
Hello

Just in case you didn't manually tried it, I updated CASCExtractor to use the latest version of CascLib (it was still using one from september).

**Comment by ladislav-zezula** [comment]
That was a terrible bug in the code. Fixed in commit ada7e4dac4f7e07d5185d11ab87f0ef3b598ab53.
Number of unknown files in WoW build 19116 went down from about 40K to 8062 files.

**Comment by spectras** [comment]
Rebuilt with latest master, and I confirm it works for me now.
Thanks for fixing it, it's cool being able to extract files from wow.

**Comment by fredy-owlr** [comment]
Do you have an updated hash listfile for patch 6.1
it has new items that aren't listed.
is there a way to generate this listfile?
thanks

**Comment by ladislav-zezula** [comment]
I don't have updated listfile. And there is no way to generate it apart from hooking the appropriate WoW function and playing the game for like eternity until all files have been opened.

**Comment by fredyjacoub** [comment]
well i was hoping to get the new music files from blackrock foundry raid.
