### ISSUE TITLE
Need a little help compiling

### ISSUE THREAD

**Issue by CookiePl0x** [ladislav-zezula/CascLib#120]
I'm having an issue compiling the casclib on Linux, any help?

![grafik](https://user-images.githubusercontent.com/13744383/47615668-f805db00-dab1-11e8-8380-ffc4fd2a6fa6.png)

I'm trying to use it with:
https://github.com/maxemann96/ghostpp

Thanks in advance!

**Comment by ladislav-zezula** [comment]
Fixed in commit 26e1f651f05a948f14b515b7ca4c7388b15ca7c5. Thanks for reporting.
