### ISSUE TITLE
new tact key

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#121]
I can't seem to push anything to the repo right now, sorry, but there's a new key to add:
 816F00C1322CDF52  6F832299A7578957EE86B7F9F15B0188 salsa20  122 WOW-26287patch8.0.1_Beta  snowkid

**Comment by ladislav-zezula** [comment]
Added in commit 026d87c1f69397ee0881e27cad8fda9fcd16db52. Also, CascView rebuilt.

**Comment by WainPetopia** [comment]
Thanks! :)
