### ISSUE TITLE
New key (vulpine mount)

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#124]
Hi Ladik,
I'm away from my PC for a few days so I can't make a pull request, but I was wondering if you could please add the following WoW key (the first part is already in your database, so just replace it):
`66033F28DC01923C  9F9519861490C5A9FFD4D82A6D0067DB   239 WOW-28294patch8.1.0_PTR  vulpine familiar mount`

Thanks! :)

**Comment by ladislav-zezula** [comment]
Added in commit 0a05974c51463b73687edfe1a8a597e184f3e6cd. Thank you for the tremendous work.
