### ISSUE TITLE
Open CASC while game is running.

### ISSUE THREAD

**Issue by stijnherfst** [ladislav-zezula/CascLib#126]
it is currently not possible to open a CASC archive while the archive is also being used by Warcraft III. 

Changing [this line](https://github.com/ladislav-zezula/CascLib/blob/a82723d2004f993e930162d59cfd0c8ca24db1dc/src/common/FileStream.cpp#L56) from:
`DWORD dwWriteShare = (pStream->dwFlags & STREAM_FLAG_WRITE_SHARE) ? FILE_SHARE_WRITE : 0;`  
to
`DWORD dwWriteShare = FILE_SHARE_WRITE;`
Fixes the issue, but now opens everything with write share. It would be useful if we could pass a flag to the openStorage function to enable write sharing.

**Comment by ladislav-zezula** [comment]
Sure I could add a flag into CascOpenFile. However, this is not a good idea.

CASC archives are designed that at any point, the game might load new or extra data into the containers. This means that while it's open by CascLib, the data might change at any point, which would bring instabilities and/or unexpected scenarios.

**Comment by stijnherfst** [comment]
It does seem like functionality that would be very handy to have. Before I changed the write sharing flag the users of my world editor had to close the game and original world editor before they could use mine. The game and original WE can also run concurrently so it does seem possible.

**Comment by tzarc** [comment]
I'd made a similar change to this back when CASC support was first added to WoW (around the 6.x mark) -- one problem I'd get very frequently was that the Battle.Net app would require a full scan and repair if it attempted to do any updates while CascLib had the files open. 

I'd advise against it, just purely from that perspective alone. For my scenario, I was mainly using it for map data -- it was easier for me to load from the CDN directly, and store into a local sqlite DB.

**Comment by ladislav-zezula** [comment]
I decided not to add this. It would help one user, but caused many additional troubles to others, who would then go here to complain about corrupted archives.
