### ISSUE TITLE
new tact key for flying pig

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#129]
Sorry, I'm away and can't submit a pull request, but the TACT key for the flying pig is now available:

    { 0x0B68A7AF5F85F7EEULL, { 0x27, 0xAA, 0x01, 0x10, 0x82, 0xF5, 0xE8, 0xBB, 0xBD, 0x71, 0xD1, 0xBA, 0x04, 0xF6, 0xAB, 0xA4 } },   // 236 WOW-28151patch8.1.0_PTR   encrypted06 Flying pig mount

Thanks :)

**Comment by ladislav-zezula** [comment]
Re: [ladislav-zezula/CascLib] new tact key for flying pig (#129)


Hi,

here:
https://github.com/ladislav-zezula/CascLib/commit/cf3ef3c4f97b29652801bc1835bdb881a7eae976

CascView rebuilt and uploaded.

L.







Sorry, I'm away and can't submit a push request, but the TACT key for the flying pig is now available:
{ 0x0B68A7AF5F85F7EEULL, { 0x27, 0xAA, 0x01, 0x10, 0x82, 0xF5, 0xE8, 0xBB, 0xBD, 0x71, 0xD1, 0xBA, 0x04, 0xF6, 0xAB, 0xA4 } },   // 236 WOW-28151patch8.1.0_PTR   encrypted06 Flying pig mount
Thanks :)
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.





--
S pozdravem,
 Ladislav Zezula
 mailto:zezula@volny.cz

**Comment by NovikDmitry** [comment]
Hi, I want to extract new cinematic from Battle of Dazar'alor, but when I extract videos I get the error "The specified file is encrypted and can not be decrypted by this user." Files bfa 810 akt and bfa 810 dor. I assume that this is the new commercials. The key was updated, the listfile too.

**Comment by WainPetopia** [comment]
Thanks! I'm about to submit a few more keys that were added since I opened this issue. I thought I did so a few days ago but I can't see the issue, so I guess it didn't submit :/

**Comment by WainPetopia** [comment]
> 
> 
> Hi, I want to extract new cinematic from Battle of Dazar'alor, but when I extract videos I get the error "The specified file is encrypted and can not be decrypted by this user." Files bfa 810 akt and bfa 810 dor. I assume that this is the new commercials. The key was updated, the listfile too.

Odd, the keys I added in commit 4c03c150d86545c42bf22d69397fcf8d91cd37c0 should have included those cinematics:

>     { 0x14C4257E557B49A1ULL, { 0x06, 0x4A, 0x97, 0x09, 0xF4, 0x2D, 0x50, 0xCB, 0x5F, 0x8B, 0x94, 0xBC, 0x1A, 0xCF, 0xDD, 0x5D } },   // 242 WOW-28440patch8.1.0_PTR   dor cinematic
> { 0x1254E65319C6EEFFULL, { 0x79, 0xD2, 0xB3, 0xD1, 0xCC, 0xB0, 0x15, 0x47, 0x4E, 0x71, 0x58, 0x81, 0x38, 0x64, 0xB8, 0xE6 } }, // 243 WOW-28440patch8.1.0_PTR   akt cinematic

**Comment by NovikDmitry** [comment]
> > Hi, I want to extract new cinematic from Battle of Dazar'alor, but when I extract videos I get the error "The specified file is encrypted and can not be decrypted by this user." Files bfa 810 akt and bfa 810 dor. I assume that this is the new commercials. The key was updated, the listfile too.
> 
> Odd, the keys I added in commit [4c03c15](https://github.com/ladislav-zezula/CascLib/commit/4c03c150d86545c42bf22d69397fcf8d91cd37c0) should have included those cinematics:
> 
> > ```
> > { 0x14C4257E557B49A1ULL, { 0x06, 0x4A, 0x97, 0x09, 0xF4, 0x2D, 0x50, 0xCB, 0x5F, 0x8B, 0x94, 0xBC, 0x1A, 0xCF, 0xDD, 0x5D } },   // 242 WOW-28440patch8.1.0_PTR   dor cinematic
> > ```
> > { 0x1254E65319C6EEFFULL, { 0x79, 0xD2, 0xB3, 0xD1, 0xCC, 0xB0, 0x15, 0x47, 0x4E, 0x71, 0x58, 0x81, 0x38, 0x64, 0xB8, 0xE6 } }, // 243 WOW-28440patch8.1.0_PTR   akt cinematic
> 
> Are you sure you have the latest CascView?


Reinstalled the program, it all worked. If the program itself does not offer to be updated, then I did not update it, but simply registered a new key and listfile. Thank you for helping me ^^
