### ISSUE TITLE
Error 1392 (CORRUPT_FILE) when open folder

### ISSUE THREAD

**Issue by Jeromnimo** [ladislav-zezula/CascLib#13]
Hi Ladislav, 

several people experience this error with wow model viewer (that now uses your lib).

After investigation yesterday on a Data/ folder that have the issue, I found the root cause, but I'm not sure what is wanted behavior.

Here is the call stack that conduct to issue:
CascOpenStorage -> LoadRootFile -> LoadRootFileToMemory -> CascReadFile -> FileStream_Read

in folders that have this issue, we read less size, because we reach end of file. 
For instance, frame->Compressed = 20077362
We manage to read : (dwBytesRead in BaseFile_Read) 20077324

as dwBytesToRead != dwBytesRead , BaseFile_Read returns false, and cascade error, resulting in not readable folder.

A simple workaround is checking GetLastError() != ERROR_HANDLE_EOF together with !FileStream_Read(...), in same if. This lets folder being read in such a case (and fail in case of real failure)

Maybe a better solution would be to move BaseFile_Read return value from bool to DWORD,return 0 in case of real failure, and BwBytesRead otherwise ?

**Comment by ladislav-zezula** [comment]
Is that some PTR build of WoW?

**Comment by Jeromnimo** [comment]
No, it's a regular install. People tried a blizzard repair, They are able to play with this install without issue.
I can provide you a ftp access where Data/ folder and .build.info file are available if you want to have a deeper look.

**Comment by ladislav-zezula** [comment]
Yes, a possibility to download and subsequently try on my own would be appreciated.

**Comment by Jeromnimo** [comment]
no problem, just drop me a mail at jerome@bausse.fr, I wil wend you ftp login / pass

**Comment by ladislav-zezula** [comment]
Fixed in commit 0e25d8297b49c0d1b4cf9ce974fef82777f2e61a.

The ROOT file went 38 bytes past the end of data.029 in that storage. Also, MD5 of that block was zeroed, meaning it is not to be checked. Unpacking the incomplete file frame went OK.
