### ISSUE TITLE
more tact additions

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#130]
Thanks for the quick addition of the last key. Sorry, but there were more added just after. This time I downloaded the file and modified it (attached, I had to add a .txt suffix for it to work),
[CascDecrypt.cpp.txt](https://github.com/ladislav-zezula/CascLib/files/2813718/CascDecrypt.cpp.txt)

**Comment by ladislav-zezula** [comment]
Done.
