### ISSUE TITLE
Opening starcraft CASC data triggers re-download by battle.net

### ISSUE THREAD

**Issue by Suicidal-Insanity** [ladislav-zezula/CascLib#131]
Opening the starcraft data and keeping it open for a while seems to interfere with some sort of periodic verification process run by the battle.net client.

This triggers a warning 'Scanning game files: Looks like there's a problem with your game....", and subsequently ~1.2gb of data is redownloaded.

This also occurs when using CASCViewer to open the SC casc data. It may need to be left running in the background for an hour or two before the issue shows up.

**Comment by download-symbols** [comment]
A crucial question: Does the Battle.net agent run WHILE the storage is open by CascView?
If yes, that means that Battle.net app will receive sharing violation error when trying to verify the storage.

**Comment by Suicidal-Insanity** [comment]
Yes, the app is running

**Comment by Suicidal-Insanity** [comment]
Perhaps it can be opened in share mode, or oplocks could be employed to release the data?

**Comment by herrvigg** [comment]
It's the same for HOTS (Heroes of the Storm), the Blizz agent also tries to repair the game install if you open CASC while the game is launched. Maybe it depends how the CASC files are opened. But for me it has never really been a problem, just do one or the other. Why would you need both at same time?

**Comment by Suicidal-Insanity** [comment]
The game does not need to be launched, just the battle.net client needs to be open. And for my use-case the users will most likely have game and editor open at once and switch back and forth.

**Comment by herrvigg** [comment]
Oh that's another thing indeed.
For precision with HOTS you can still launch the agent and open the CASC archive as long as you don't start the game. If CASC is opened and you try to launch the game. then the game won't start and the agent will try to repair it. The other way around, if you launch the game then you can't open CASC but nothing happens in the agent.

**Comment by ladislav-zezula** [comment]
> Perhaps it can be opened in share mode, or oplocks could be employed to release the data?

CascLib opens the data files with:
* DesiredAccess = FILE_READ_DATA | FILE_READ_ATTRIBUTES
* ShareAccess = FILE_SHARE_READ.

Battle.net wants write access which it does not get, hence triggering repair action.
In commit ef66d7bb46f0bb4dd782d3b68eb7dcc358d52a13, I changed this and the data files (data.000, data.001, etc) are now open for write, with read+write sharing.

New build of CascView was uploaded on my website. Please, try for your case and leave me a note here whether it helped you.

**Comment by Suicidal-Insanity** [comment]
Will try it tommarow

**Comment by Suicidal-Insanity** [comment]
So far it has not triggered a redownload. Thanks!

**Comment by download-symbols** [comment]
Good. We will see whether it will not trigger another problems. One of the candidates: What will happen if the game will update itself while the storage is open by CascView.

**Comment by ladislav-zezula** [comment]
Good. We will see whether it will not trigger another problems. One of the candidates: What will happen if the game will update itself while the storage is open by CascView.
