### ISSUE TITLE
FileDataId is set to CASC_INVALID_ID if filename is unknown

### ISSUE THREAD

**Issue by Qartar** [ladislav-zezula/CascLib#136]
When iterating over files in storage, files that are only found by CKEY (i.e. files without a listfile entry) have their `FileDataId` set to `CASC_INVALID_ID`, even though the `FileDataId` is known and stored inside the FileTree. (cf. `ParseWowRootFile_AddFiles`). This is especially important for WoW 8.2 as it seems many files are being added without a filename hash at all, requiring the use of the file id for identification.

**Comment by ladislav-zezula** [comment]
I am currently working on support for 8.2 and this was one of the issues I found. It'll be solved as part of overall update for 8.2.

Thank for the bug report.

**Comment by ladislav-zezula** [comment]
Should be fixed in commit ee25fd6dd1dd7becdd0fae2b3660372fa04c8b7a. The work on 8.2 is still ongoing.

**Comment by Qartar** [comment]
Thanks for your work on this! A few observations:

* There was a regression of sorts from ee25fd6 to dd6fd36. Before your last commit you could iterate over all file ids, it looks like it now only iterates over unique content keys which means that duplicate files with the same ids get skipped (unless they've been named in the listfile). I've notice this happens a lot for minimap tiles since the edges are contiguous file ids and often just a constant background color (i.e. binary identical). I expect this was changed to fix the behavior in ee25fd6 which was iterating over every file twice, not sure if this result was intended but I think there should definitely be a way to iterate over every file id, regardless of whether it points to unique file contents.

* Named internal files now get added with unique ids instead of `CASC_INVALID_ID` (due to [this change](https://github.com/ladislav-zezula/CascLib/commit/ee25fd6dd1dd7becdd0fae2b3660372fa04c8b7a#diff-a1301a086afb108bb84bdd1f461ed024R91)) which seems incorrect to me since files added later may use those ids and the ids for the internal files will change more or less every update. Do these files need to have valid ids for internal consistency? Otherwise I'd rather they kept using `CASC_INVALID_ID`.

* It looks you're unintentionally skipping the very last locale block. See `TRootHandler_WoW::CaptureRootGroup` [here](https://github.com/ladislav-zezula/CascLib/blob/dd6fd36e4474c2693f3928610df4e1595584f2f7/src/CascRootFile_WoW.cpp#L148), [here](https://github.com/ladislav-zezula/CascLib/blob/dd6fd36e4474c2693f3928610df4e1595584f2f7/src/CascRootFile_WoW.cpp#L158), and [here](https://github.com/ladislav-zezula/CascLib/blob/dd6fd36e4474c2693f3928610df4e1595584f2f7/src/CascRootFile_WoW.cpp#L166). If the file ends exactly at the end of the block then the block will be skipped due to the `return NULL`, but you should be able to read that block just fine. Should those comparisons be `>` instead of `>=`?

* What happened to `CascGetFileId`?

**Comment by ladislav-zezula** [comment]
> Named internal files now get added with unique ids instead of CASC_INVALID_ID (due to this change) > Do these files need to have valid ids for internal consistency? 

Yes. The client of CascLib will either open a file by name or by ID. For that purpose, it is necessary that all files have either attribute. The value of the ID is negotiable and not really dependable on anything, as you get that ID during CascFind(First|Next)File.

> What happened to CascGetFileId?

Gone. It's no longer possible to keep this API working. Before patch 8.2, there was a clear unique mapping of FileName -> FileHash -> ROOT entry with FileDataId. This is no longer possible.

I'll check the rest.

**Comment by ladislav-zezula** [comment]
> It looks you're unintentionally skipping the very last locale block.

Fixed in commit 1ff2a667f0d978dbf18d1cfbcb010b0e33902a21.

**Comment by ladislav-zezula** [comment]
>  I've notice this happens a lot for minimap tiles since the edges are contiguous file ids and often just a constant background color (i.e. binary identical)
Could you please provide me a concrete example? I am aware that the search algorithm is not perfect and trying to find a best solution.

**Comment by Qartar** [comment]
[Here](https://gist.github.com/Qartar/307f0208eb01cae66ed40989eb9dffa6) is a diff of my "manifest" file from ee25fd6 to dd6fd36. It's organized into columns, fileid, hash, filename. You can ignore the initial group of files with fileid 0; those are all the files that were still being returned by CKEY, never figured out exactly what was going on there. `74276cd301861c71fca28918451ffce3` is a good example as the first instance is shown in the diff (line 2174) but all subsequent instances have been removed.

**Comment by ladislav-zezula** [comment]
> those are all the files that were still being returned by CKEY
> never figured out exactly what was going on there.

This was an attempt to return files which were not found in the ROOT file. The idea is
1) Exhaust all files that are in ROOT and added extra (like ROOT, ENCODING, ...)
2) Return all remaining files.
For example, if you open CASC storage from Overwatch or Call of Duty, the ROOT file only contains few files. Since I never figured the format of the rest of the files, I return them by CKey at least.

> 74276cd301861c71fca28918451ffce3 is a good example as the first instance is shown in the diff

Oh boy. Same content, different IDs. A nightmare. Let me think of a solution.

**Comment by ladislav-zezula** [comment]
Check the following commit:
https://github.com/ladislav-zezula/CascLib/commit/b7ab31b82a2c524f9a2f01654c8bde11c9356682
I basically reverted the part. Duplicated files will not be excluded during the ROOT search phase.

Could you please check with your tool whether it's OK?

> What happened to CascGetFileId?

How badly do you need this? I can add a limited support for it in form of CascGetFileInfo(FileDataId). But I am not very keen to peek an API function that is there only for one of the games, moreover when the feature will be less and less useful as the files in the storage no longer have names.

**Comment by Qartar** [comment]
This works for me since I have logic for filtering out the duplicates, thank you! I don't actually need `CascGetFileId`, just asking because I've been maintaining a C++ wrapper for the library (https://github.com/Qartar/CascLibPlus) and was curious if it would be coming back at some point.

For what it's worth, I've given up on have any unique keys, my internal data structure for the "manifest" files looks like this:
```cpp
struct File {
    int32_t id;
    md5_hash hash;
    std::string name;
};

std::vector<File> _files;
std::multimap<int32_t, std::size_t> _id_to_index;
std::multimap<md5_hash, std::size_t> _hash_to_index;
std::multimap<std::string, std::size_t> _name_to_index;
```
I don't recommend `std::multimap`, works okay for me but performance and interface are both pretty awful.

**Comment by ladislav-zezula** [comment]
Good. I am closing this now.

BTW, as for performance, I did quite a hackery in CascLib in order to keep things fast. When you are talking about a million files, it really does matter :-)
