### ISSUE TITLE
Syntax error in CascReadFile.cpp

### ISSUE THREAD

**Issue by herrvigg** [ladislav-zezula/CascLib#146]
hello,
after a few months working on a fork without problem, i just resynched to the last commit in master. But the project now seems broken, it doesn't compile. What happened here to CascReadFile.cpp?

https://github.com/ladislav-zezula/CascLib/blob/456549056255f0ebaf80bc8b1bb6ab15f751d52a/src/CascReadFile.cpp#L657-L677

NB: also, not sure why some DLLs were added to the project at a certain point. In general git repos should not contain binaries. Good you got rid of them :)
But i noticed the .gitignore changed, now allowing those DLLs which look a bit strange: https://github.com/ladislav-zezula/CascLib/commit/993c64f9e483972c16b3bcb2ef1952a71a3abd5b#diff-a084b794bc0759e7a6b77810e01874f2

**Comment by ladislav-zezula** [comment]
Hi,
ohh, sorry, this was a terrible mistake that I accidentally somehow merged `development` branch into master. The bad commit reverted. Should be OK now.

**Comment by herrvigg** [comment]
Great, now it can build (i'm using VS2017). Many thanks! 😄  

Now compared to my previous state there are only these things removed from .gitignore:
```
*.dll
*.lib
/Win32/
/Debug/
bin/
```

If it were only for me it would be enough to gitignore the `bin/` directory. All the rest is created under that one with the default settings. I use CascLib exactly as it is, which is very convenient :)

**Comment by ladislav-zezula** [comment]
I'll think about the binaries. The thing is, some people contact me that they don't know how to build the DLL (despite I think CascLib is easy to build, without any extra dependencies).
