### ISSUE TITLE
identifiers started with prefix __ are reserved for C++ standard libraries to use. Using them are undefined behaviors

### ISSUE THREAD

**Issue by euloanty** [ladislav-zezula/CascLib#148]

**Comment by ladislav-zezula** [comment]
Which identifiers in particular do you mean?

**Comment by euloanty** [comment]
For example:
__LOOKUP3_H__
undefined behavior
https://github.com/ladislav-zezula/CascLib/blob/master/src/jenkins/lookup.h


Cppreference:
https://en.cppreference.com/w/cpp/language/identifiers
In declarations
An identifier can be used to name objects, references, functions, enumerators, types, class members, namespaces, templates, template specializations, parameter packs, goto labels, and other entities, with the following exceptions:

the identifiers that are keywords cannot be used for other purposes;
the identifiers with a double underscore anywhere are reserved;
the identifiers that begin with an underscore followed by an uppercase letter are reserved;
the identifiers that begin with an underscore are reserved in the global namespace.
"Reserved" here means that the standard library headers #define or declare such identifiers for their internal needs, the compiler may predefine non-standard identifiers of that kind, and that name mangling algorithm may assume that some of these identifiers are not in use. If the programmer uses such identifiers, the behavior is undefined.

In addition, it's undefined behavior to #define or #undef names identical to keywords. If at least one standard library header is included, it's undefined behavior to #define or #undef identifiers identical to names declared in any standard library header.
