### ISSUE TITLE
Updating CascLib to 64-bit filesize

### ISSUE THREAD

**Issue by ladislav-zezula** [ladislav-zezula/CascLib#151]
I am going to merge current development branch (https://github.com/ladislav-zezula/CascLib/tree/development) into master. This new version supported multi-span files - files that go over multiple CKey blocks.  These files can (and typically are) greater than 4 GB in size.

Unfortunately, it will introduce several compiling incompatibilities:
* `CascGetFileSize` can now use also upper 32-bits of file size
* `CascSetFilePointer` can now use also upper 32-bits of the file size
* `CascFind(First|Next)File`'s structure `CASC_FIND_DATA` has some members renamed and `FileSize` member is now 64-bit.

@WainPetopia, @Shauren, @Jeromnimo, I have a thing to ask: Could you check how much work with your projects will this mean? Please, clone the repo, checkout the `development` branch and check how much compile errors will you get.

**Comment by Jeromnimo** [comment]
Thanks your continuous work on this Ladislav. Will have a try next week (no computer access this week end and let you know ASAP.

**Comment by Shauren** [comment]
Almost unaffected (only rename of dwBuildNumber to BuildNumber), I don't use listfiles (so no search), working exclusively with file data ids from db2 files

Also, a couple errors within CascLib itself
```
2>C:\Users\shaur\Desktop\Sources\TrinityCore\dep\CascLib\src\CascCommon.cpp(43,41): error C2275:  'BYTE': illegal use of this type as an expression
2>C:\Users\shaur\Desktop\Sources\TrinityCore\dep\CascLib\src\CascCommon.cpp(105,41): error C2275:  'BYTE': illegal use of this type as an expression
2>C:\Users\shaur\Desktop\Sources\TrinityCore\dep\CascLib\src\CascCommon.cpp(138,1): error C2084:  function 'void FreeCascBlob(PQUERY_KEY)' already has a body
2>C:\Users\shaur\Desktop\Sources\TrinityCore\dep\CascLib\src\CascCommon.h(422): message :  see previous definition of 'FreeCascBlob'
```

**Comment by ladislav-zezula** [comment]
@Shauren: `CascCommon.cpp` no longer exists in the `development` branch.

**Comment by Shauren** [comment]
I guess I should have deleted the entire dir instead of just dropping in development branch on top of it but either way, this change doesn't affect me

**Comment by WainPetopia** [comment]
In WMV I changed the file size vars to double, and it seemed to compile and run fine with your research branch. I'm not sure I caught everything (are chunks still int 32?) but I don't think we'll have any trouble updating. :)

Unrelated, could you please remind me what funcs you added so we could include custom TACT keys? I couldn't find it.

Thanks :)

**Comment by ladislav-zezula** [comment]
@WainPetopia: It's CascAddEncryptionKey():
http://www.zezula.net/en/casc/casclib/cascaddencryptionkey.html

**Comment by WainPetopia** [comment]
> > Unrelated, could you please remind me what funcs you added so we could include custom TACT keys? I couldn't find it.
> 
> @WainPetopia: It's CascAddEncryptionKey():
> http://www.zezula.net/en/casc/casclib/cascaddencryptionkey.html
Thanks! Any idea how I'd convert the key from a QString to an LPBYTE to pass to your function? Say, the key is "465D784F1019661CCF417FE466801283".
I tried: keyBytes = QByteArray::fromHex(key.toUtf8());
Then I passed keyBytes.data() to your function. It gave no errors, but it doesn't seem to have worked. The file remains encrypted. I've tried a lot of other things but had no luck so far.  Thanks!

**Comment by ladislav-zezula** [comment]
I guess the best will be that I add an extra function doing the same thing like CascAddEncryptionKey, but taking a hexa string as parameter

**Comment by WainPetopia** [comment]
That sounds ideal! Thanks. LPBYTE doesn’t seem like a common data type and nothing that other people have suggested has helped, unfortunately.

**Comment by ladislav-zezula** [comment]
Try `CascAddStringEncryptionKey`.
https://github.com/ladislav-zezula/CascLib/commit/eaeb48c0aa4f551af03116edf0d209711b9f7fe5

**Comment by WainPetopia** [comment]
I'm trying to test it on your development branch. I include the right branch commit, but get the error:
error C3861: 'CascAddStringEncryptionKey': identifier not found
Not sure why :/

**Comment by ladislav-zezula** [comment]
I recommitted, try to `git pull` and rebuilt.
It's here: https://github.com/ladislav-zezula/CascLib/blob/development/src/CascLib.h#L346

**Comment by WainPetopia** [comment]
Thanks. It builds now :)  But the new function still won't add my key, for some reason.

The code is basically: 
```
QString keyName = "259EE68CD9E76DBA", keyValue = "465D784F1019661CCF417FE466801283";
bool ok, funcReturn;
funcReturn = CascAddStringEncryptionKey(hStorage, keyName.toULongLong(&ok, 16), keyValue.toStdString().c_str());
LOG_INFO << "Adding extra tact key:" << keyName << ":" << keyValue << ", funcReturn =" << funcReturn << ", error =" << GetLastError();  
```
It logs:
Adding extra tact key: "259EE68CD9E76DBA" : "465D784F1019661CCF417FE466801283" , funcReturn = false , error = 0

I have a test version of CascLib where that key has been deleted (it's the key for the new Alabaster mounts) and they won't load.

**Comment by ladislav-zezula** [comment]
The situation corresponds to inserting an existing key. I changed the code so that it now properly sets LastError to `ERROR_ALREADY_EXISTS`. Could you 'git pull' and try again?

P.S. Sorry for kinda long delays, I am on vacation on the mountains and am not exactly always online or in front of the PC :-)

**Comment by WainPetopia** [comment]
Thanks Ladik!

First of all, I'm sorry to trouble you on your vacation! You should be ignoring me :)

Secondly, it now works. I found there was also an error on my end that meant sometimes I was calling the function before the storage was defined. That's now fixed.

Do you plan to port this to the main branch? Or wait until the development branch is merged? :)

Thanks again! 

Wayne

**Comment by ladislav-zezula** [comment]
Yes, I plan to merge the development branch as soon as I get home. I didn't want to do it before vacation, as it's generally a terrible idea.

However, feel free to use the development branch now. It passed my tests and I don't plan to do any more changes before implementing Ribbit protocol for online storages.

**Comment by WainPetopia** [comment]
Thanks again. I’ll probably wait until you merge the branches, unless that’s still a long way away. 

Enjoy your vacation :)

**Comment by ladislav-zezula** [comment]
Merged: https://github.com/ladislav-zezula/CascLib/pull/154
