### ISSUE TITLE
Dropped support for CascStorageInstalledLocales

### ISSUE THREAD

**Issue by Shauren** [ladislav-zezula/CascLib#155]
`development` branch that changed file sizes to 64 bit silently dropped `CascStorageInstalledLocales` for `CascGetStorageInfo` without deleting the enum value so my code that was using it started to fail at runtime instead of failing to compile.

What is the new way of retrieving available locales? (wow only)

**Comment by ladislav-zezula** [comment]
There is none. Seeing that people are using it, I'll put it back.

**Comment by ladislav-zezula** [comment]
Fixed in commit b91f87c770c78340dcd96df970e55b5c0469e884.

**Comment by Shauren** [comment]
Thanks, works just like before
