### ISSUE TITLE
Mac OS X building fails

### ISSUE THREAD

**Issue by skarnproject** [ladislav-zezula/CascLib#156]
Building on Mac OS X fails with the following error:
`Scanning dependencies of target casc
[  3%] Building CXX object CMakeFiles/casc.dir/src/common/Common.cpp.o
/Users/username/Downloads/CascLibPlus-master/lib/CascLib/src/common/Common.cpp:235:25: error: use of undeclared identifier 'wcslen'
            cchSource = wcslen(szSource);
                        ^
/Users/username/Downloads/CascLibPlus-master/lib/CascLib/src/common/Common.cpp:267:25: error: use of undeclared identifier 'wcslen'
            cchSource = wcslen(szSource)
                        ^
/Users/username/Downloads/CascLibPlus-master/lib/CascLib/src/common/Common.cpp:290:24: error: use of undeclared identifier 'vsnprintf'
    buffend = buffer + vsnprintf(buffer, nCount, format, argList);
                       ^
/Users/username/Downloads/CascLibPlus-master/lib/CascLib/src/common/Common.cpp:310:24: error: use of undeclared identifier 'vswprintf'
    buffend = buffer + vswprintf(buffer, nCount, format, argList);
                       ^
/Users/username/Downloads/CascLibPlus-master/lib/CascLib/src/common/Common.cpp:347:19: error: use of undeclared identifier 'wcslen'
        nLength = wcslen(szString);
                  ^
/Users/username/Downloads/CascLibPlus-master/lib/CascLib/src/common/Common.cpp:422:23: warning: passing an object that undergoes default argument promotion
      to 'va_start' has undefined behavior [-Wvarargs]
    va_start(argList, chSeparator);
                      ^
/Users/username/Downloads/CascLibPlus-master/lib/CascLib/src/common/Common.cpp:417:60: note: parameter of type 'char' is declared here
size_t CombinePath(LPTSTR szBuffer, size_t nMaxChars, char chSeparator, ...)
                                                           ^
1 warning and 5 errors generated.
make[2]: *** [CMakeFiles/casc.dir/src/common/Common.cpp.o] Error 1
make[1]: *** [CMakeFiles/casc.dir/all] Error 2
make: *** [all] Error 2
Sergeys-MBP-2:build username$ 
`

**Comment by bloerwald** [comment]
```
diff --git a/src/common/Common.cpp b/src/common/Common.cpp
index 1fc6cc9..aed32db 100644
--- a/src/common/Common.cpp
+++ b/src/common/Common.cpp
@@ -8,10 +8,13 @@
 /* 29.04.14  1.00  Lad  The first version of CascCommon.cpp                  */
 /*****************************************************************************/
 
+
 #define __CASCLIB_SELF__
 #include "../CascLib.h"
 #include "../CascCommon.h"
 
+#include <cwchar>
+
 //-----------------------------------------------------------------------------
 // Conversion to uppercase/lowercase
 
diff --git a/src/common/FileStream.cpp b/src/common/FileStream.cpp
index cd3300a..6b2a12a 100644
--- a/src/common/FileStream.cpp
+++ b/src/common/FileStream.cpp
@@ -17,6 +17,8 @@
 #include "../CascLib.h"
 #include "../CascCommon.h"
 
+#include <cstdio>
+
 #ifdef _MSC_VER
 #pragma comment(lib, "wininet.lib")             // Internet functions for HTTP stream
 #pragma warning(disable: 4800)                  // 'BOOL' : forcing value to bool 'true' or 'false' (performance warning)
```

fixes the errors above. As for the warnings emitted, 

```
/CascLib/src/common/ListFile.cpp:202:82: warning: result of comparison of constant 133 with expression of
      type 'char' is always false [-Wtautological-constant-out-of-range-compare]
        if(pCache->pPos[0] == 0x0A || pCache->pPos[0] == 0x0D || pCache->pPos[0] == 0x85)
                                                                 ~~~~~~~~~~~~~~~ ^  ~~~~
1 warning generated.
```

would be the most important, which is fixed by

```
diff --git a/src/common/ListFile.cpp b/src/common/ListFile.cpp
index a2239e1..d7ec314 100644
--- a/src/common/ListFile.cpp
+++ b/src/common/ListFile.cpp
@@ -199,7 +199,7 @@ size_t ListFile_GetNextLine(void * pvListFile, const char ** pszLineBegin, const
     {
         // If we have found a newline, stop loading
         // Note: the 0x85 char came from Overwatch build 24919
-        if(pCache->pPos[0] == 0x0A || pCache->pPos[0] == 0x0D || pCache->pPos[0] == 0x85)
+        if(pCache->pPos[0] == '\x0A' || pCache->pPos[0] == '\x0D' || pCache->pPos[0] == '\x85')
             break;
 
         // Blizzard listfiles can also contain information about patch:
```

**Comment by ladislav-zezula** [comment]
Please, do not put extra includes (`#include <cwchar>`, `#include <cstdio>`) directly into CPP files. They belong to CascPort.h, in the specified section (in your case `PLATFORM_MAC`)

**Comment by bloerwald** [comment]
Those includes are from the C++ standard, not macOS, so it should be fine on any platform ;) Regardless, feel free to put them there instead, I can’t exactly push to your repository anyway :)

**Comment by ladislav-zezula** [comment]
>  I can’t exactly push to your repository anyway :)

You can clone the repo and create pull request. But OK, I'll do it

**Comment by ladislav-zezula** [comment]
Fixed in branch `mac_build`. Please, clone the repo, switch to `mac_build` and try if it fixes the warnings. Once you confirm, I merge the `mac_build` branch to `master`.
