### ISSUE TITLE
Can't open Diablo PTR CASC 

### ISSUE THREAD

**Issue by nongnoobjung** [ladislav-zezula/CascLib#16]
Can't open Diablo PTR CASC 

it not have list file

**Comment by ladislav-zezula** [comment]
Guess someone will have to make one.

**Comment by Tuz** [comment]
Try this listfile:

Base
enUS
enGB
deDE
enSG
ruRU
koKR
frFR
zhCN
esES
zhTW 
enCN
enTW
esMX
ptBR 
itIT
ptPT
Windows
OSX

**Comment by ladislav-zezula** [comment]
This is not a listfile. Could you please explain what do you mean?

**Comment by p0d3x** [comment]
The root file has a different layout and contains the entries Tuz posted. Each of those entries/files contains 3 different types of file lists. The files can be read using this 010 editor template:

    typedef struct {
        unsigned byte encodingKey[16];
        string fname;
    } ROS_ROOT_NAMED_ENTRY;

    typedef struct {
        unsigned byte encodingKey[16];
        DWORD snoId;
    } ROS_ROOT_ENTRY_0;

    typedef struct {
        unsigned byte encodingKey[16];
        DWORD unk0[2];
    } ROS_ROOT_ENTRY_1;

    struct {
        DWORD dwMagic;
        DWORD nEntries0;
        ROS_ROOT_ENTRY_0 entries0[nEntries0]<optimize=false>;
        DWORD nEntries1;
        ROS_ROOT_ENTRY_1 entries1[nEntries1]<optimize=false>;
        DWORD nNamedEntries;
        ROS_ROOT_NAMED_ENTRY namedEntries[nNamedEntries]<optimize=false>;
    } ROS_ROOT_FILE;

snoId is an asset id of diablo3, unk0[2] is a combination of a snoId and another int.
to get a list of all available assets (snoIds+sno group+ asset name), you need to load "CoreTOC.dat", which is in the entries0 array of the "Base" file. The sno groups infer file path+extension.

**Comment by ladislav-zezula** [comment]
Why oh why must Blizzard make separate ROOT file format for each game ....
Oh well. Let me work on it for a while before we can actually open something.

**Comment by nongnoobjung** [comment]
@ladislav-zezula if finish  can you update casc version at www.zezula.net/en/casc/main.html ?

**Comment by ladislav-zezula** [comment]
When I am finished, I will.

**Comment by ladislav-zezula** [comment]
Partial support added in commit 501a3e05a09a66ebca2e3a5e974cba6b3c9e4cd9.
However, it is still not complete, there is only a very few actual file names.

**Comment by ladislav-zezula** [comment]
(Almost) complete support added in commit ff441f32c0e6c02089e409da45c62aa1983ca276.
Missing support for providing valid extensions of sub-files, like Base\SoundBank\3D Ambience\0000.xxx.

**Comment by nongnoobjung** [comment]
thank you again
