### ISSUE TITLE
Black Ops 4?

### ISSUE THREAD

**Issue by TheNeoTV** [ladislav-zezula/CascLib#163]
Missing also the Game Black Ops 4 it also uses casc file system. can it please be implemented?

**Comment by ladislav-zezula** [comment]
Call of Duty Black Ops is indeed supported. Where exactly do you want it to be added?

**Comment by TheNeoTV** [comment]
idk i have tested it but not found how to open it. But will be cool if it can come to the casc explorer

**Comment by ladislav-zezula** [comment]
TOM_RUS is the author of CASCExplorer.

**Comment by TheNeoTV** [comment]
Yes and it uses casc lib so we needthe black ops 4 stuff in the casclibs please :O

**Comment by ladislav-zezula** [comment]
He uses a library that is indeed called CascLib, but it's not mine.

**Comment by TheNeoTV** [comment]
and that is the question that you can add it in general?!

**Comment by ladislav-zezula** [comment]
My CascLib supports Call of Duty 4: Black Ops flawlessly. My tool, CascView, supports Call of Duty 4: Black Ops flawlessly. I really don't know what more can I do.
