### ISSUE TITLE
Can't read files if the game is running

### ISSUE THREAD

**Issue by bastiflew** [ladislav-zezula/CascLib#169]
Hi,
the comment at this line https://github.com/ladislav-zezula/CascLib/blob/8b9d769e4aceebd61cb684113fff9ecd08ba9467/src/CascFiles.cpp#L1507
says the method fails if the game is running.
If I add the flag `STREAM_FLAG_WRITE_SHARE`, it works even with the game running.
Any reason to not add this flag ?

**Comment by ladislav-zezula** [comment]
The comment is obsolete there. CascLib works with game running already.

**Comment by bastiflew** [comment]
I should have comment a bit more, you can't do a `OpenCascStorage()` with Diablo III running, unless `STREAM_FLAG_WRITE_SHARE` is added to `FileStream_OpenFile()`
Otherwise, `CreateFile` generate an error 32.

**Comment by ladislav-zezula** [comment]
Could you please try this build?
http://www.zezula.net/download/cascview_en_bastiflew.zip

**Comment by boskee** [comment]
@ladislav-zezula This build certainly fixed my issue #170

**Comment by boskee** [comment]
@ladislav-zezula Having tested it myself on Diablo 3 - this build also seems to work with a running copy of D3, while build 197 doesn't (shows not enough memory error).

**Comment by bastiflew** [comment]
The issue is the same with the latest version in master. And there's another issue with file extraction, I will create another issue.
