### ISSUE TITLE
[Diablo III] Files are corrupted / contain bad data

### ISSUE THREAD

**Issue by bastiflew** [ladislav-zezula/CascLib#171]
I used to use a CascLib from last year (around decembre 2018), and everything was fine with this version.
Yesterday I pull the master branch, and tried to extract some files.
Most of them was corrupted with bad data I guess, but some of them was correct.
Note that none of the api call failed, everything was fine during the extraction.

**Comment by ladislav-zezula** [comment]
Can you put an example of a corrupt file?
Also, could you calculate the MD5 of a file and compare it with CKey (RightClick - Properties - CKey)?

**Comment by bastiflew** [comment]
was 100% my fault, I've created a C# wrapper for your dll, and I didn't notice that `CASC_FIND_DATA` changed.
