### ISSUE TITLE
How to parse the data from a CASC file?

### ISSUE THREAD

**Issue by xiangzhai** [ladislav-zezula/CascLib#175]
Hi,

My sincere thanks will give to @ladislav-zezula CascView!  It helps me to play the Campaigns of Warcraft 3 Reforged Beta.

But how to `Parse` the data from a CASC file with [CascReadFile](http://www.zezula.net/en/casc/casclib/cascreadfile.html)?  Is there some reverse engineering stuff about Map, Module, etc.

Thanks,
Leslie Zhai

**Comment by ladislav-zezula** [comment]
Please, specify "Parse the data". If you mean how to read images, maps and so on, then this is beyond the scope of the CascLib library.

**Comment by xiangzhai** [comment]
Hi @ladislav-zezula 

Thanks for your response!

@timfel  https://github.com/Wargus  use your StormLib for StarCraft 1 and WarCraft 2.  Then how to read the raw data about images, maps and so on for WarCraft 3?

Thanks,
Leslie Zhai

**Comment by ladislav-zezula** [comment]
Like I said. I don't deal what's inside the files. That's for another communities
