### ISSUE TITLE
Reading files from different threads fails

### ISSUE THREAD

**Issue by Naros** [ladislav-zezula/CascLib#178]
I don't believe the changes added in https://github.com/ladislav-zezula/CascLib/commit/f9fc9a255afdef4efe5c229cff6b0f7ba806ffdf are sufficient for multi-threading, unless I am mistakenly using the API wrong.

My `TaskQueue` can process tasks both on the main thread and background thread.  There are some tasks that open one or more files from CASC, parse the contents, and populate some staging class that is then used by the main thread as so read operations are theoretically asynchronous.  The problem is that `CascReadFile` returns contents that appear as though a buffer is being thrashed due to being called from multiple threads.  

If I toggle the `TaskQueue` to execute submitted tasks immediately on the main thread to bypass any of the multi-threaded behavior, the `CascReadFile` method works as I expect.  Essentially I have a smaller wrapper class that wraps the file `HANDLE` allowing reading, seeking, etc against the handle.

Are there specifically certain limitations here with multi-threading support with CASC that I'm simply not seeing or that are not yet documented?

**Comment by Naros** [comment]
I could be mistaken but after some debugging, if `FileStream_Read` is guarded by a lock inside the `ReadFile_FrameCached` method, I no longer run into issues with `CascReadFile`.  

The only outstanding issue I still face is randomly `CascOpenFile` will report that the storage handle is invalid because of CASC_MAGIC_STORAGE mismatch; which makes me wonder if there isn't still an issue somewhere causing memory corruption.

This is all from the perspective of Linux, no idea if Windows would behave differently.

**Comment by Naros** [comment]
As a quick follow-up, there is also the occasional hiccupt with `CascGetFileSize64` where the method call to `EnsureFileSpanFramesLoaded` fails with `ERROR_FILE_NOT_FOUND` too.

**Comment by ladislav-zezula** [comment]
Sorry for responding so late. Been kinda busy with all the pre-Christmas stuff.

I was checking your problem and I'll probably add a file-level synchronization to `ReadFile_FrameCached`. Before I would do that, I would love to know where the problem exactly is.

Would it be possible to create a copy of your project, cut it to the bone so that it only multi-thread-read file data and checks whether the content is trashed?

Don't post the project here, send it directly to zezula at volny dot cz.

**Comment by Naros** [comment]
Hi @ladislav-zezula, email sent.

**Comment by ladislav-zezula** [comment]
I probably know. And the problem will not raise under Windows. The reason is that Windows can issue a read operation at a certain offset. Linux needs to do it using `lseek64` + `read/write`, which is not atomic. The reason you are getting corrupted data is that multiple thread may set the file pointer, then issue a read file on an offset different than intended.

**Comment by Naros** [comment]
I attempted to modify `TBaseProviderData` such that the `File` struct looked like the following:
```
    struct
    {
        ULONGLONG FileSize;                 // Size of the file
        ULONGLONG FilePos;                  // Current file position
        ULONGLONG FileTime;                 // Last write time
        HANDLE hFile;                       // File handle
		#if defined(PLATFORM_MAC) || defined(PLATFORM_LINUX)
        CASC_LOCK lock;						// File lock
		#endif
    } File;
```
Inside `BaseFile_Open`, I called `CascInitLock(pStream->Base.File.lock)` and then inside `BaseFile_Close` I called `CascFreeLock(pStream->Base.File.lock)`.  I then inside `BaseFile_Read`, I attempted to wrap the `lseek + read` by locking that lock and unlocking it when done.  This worked pretty well except on occasion I would get Error 22 when calling `CascReadFile`.  

I'm not sure what your plan was but I think it would make the most sense to introduce a lock per file rather than a lock for all files mainly for performance reasons.

**Comment by ladislav-zezula** [comment]
> I'm not sure what your plan was but I think it would make the most sense to introduce a lock per file rather than a lock for all files mainly for performance reasons.
Yes, I definitely do want to have per-file lock. No reason to lock entire storage when a thread only needs to read single file.

**Comment by ladislav-zezula** [comment]
I made a branch created specifically for this issue:
https://github.com/ladislav-zezula/CascLib/tree/Fix_Issue_178

**Comment by ladislav-zezula** [comment]
> This worked pretty well except on occasion I would get Error 22 when calling CascReadFile

ERROR_INVALID_PARAMETER, aka EINVAL?

**Comment by Naros** [comment]
> ERROR_INVALID_PARAMETER, aka EINVAL?

Yes

**Comment by Naros** [comment]
> ERROR_INVALID_PARAMETER, aka EINVAL?

This may be a false alarm, I guess it ultimately depends on expected intent.  I have a parse that gets a block and apparently sees the block size is 0 and still attempts to call `CascReadFile` with a size value of `0`. 

I guess the real question is whether passing `0` as `dwBytesToRead` should be considered a failure or whether its considered acceptable and return true but without doing any read operations?  That aside, I ran the branch code multiple times and worked fine from what I could tell on Linux.

**Comment by ladislav-zezula** [comment]
> I guess the real question is whether passing 0 as dwBytesToRead should be considered a failure or whether its considered acceptable and return true but without doing any read operations?

`SFileReadFile(hFile, pbBuffer, 0, NULL)` actually does return `true`.

**Comment by Naros** [comment]
So doing a bit more rigorous testing, I still see CascOpenFile return false with Error 9.

The gist of my code is that I have a list of 1031 file data ids that need to be opened.  I split this list into 4 buckets, 3 for each worker thread and 1 for the main thread.  Then in a loop, each of the file data ids in the buckets are opened using `CascOpenFile`.  

If I wrap the CascOpenFile in a mutex, the problem goes away so perhaps this is some other global state that isn't being properly guarded?

**Comment by ladislav-zezula** [comment]
I found the (probable) reason why this happens. There is reference counting on archives:
* `CascOpenStorage` sets ref count to 1
* Every `CascOpenFile` increments the reference count of the archive.
* Every `CascCloseFile` decrements the reference count of the archive.
* CascCloseStorage decrements the reference count of the archive.

If the reference count of the archive drops to zero, the archive is closed. This mechanism allows the following sequence works properly:
```
CascOpenStorage
CascOpenFile
CascCloseStorage
CascCloseFile
```
However, because reference increments were not atomic under Linux, it often closed the archive during `CascCloseFile`. This issue also raised under Windows if I removed the `InterlockedIncrement/InterlockedDecrement` call and replaced it with the Linux Code.

After I put proper locking there, it no longer causes problems. However - the current fix is quite ugly and I am looking for a nice, non-STL version of `InterlockedIncrement` under Linux.

**Comment by Naros** [comment]
> After I put proper locking there, it no longer causes problems. However - the current fix is quite ugly and I am looking for a nice, non-STL version of InterlockedIncrement under Linux.

Would https://gcc.gnu.org/onlinedocs/gcc-4.4.3/gcc/Atomic-Builtins.html#Atomic-Builtins be viable?

**Comment by Naros** [comment]
I tested out this change to `CascPort.h`
```
inline DWORD CascInterlockedIncrement(DWORD & Value)
{
#ifdef PLATFORM_WINDOWS
    return (DWORD)InterlockedIncrement((LONG *)(&Value));
#elif defined(__GNUC__)
	Value = __sync_add_and_fetch(&Value, 1);
    return Value;
#else
    return ++Value;
#endif
}

inline DWORD CascInterlockedDecrement(DWORD & Value)
{
#ifdef PLATFORM_WINDOWS
    return (DWORD)InterlockedDecrement((LONG *)(&Value));
#elif defined(__GNUC__)
	Value = __sync_sub_and_fetch(&Value, 1);
	return Value;
#else
	return --Value;
#endif
}
```
It seems to work quite well, although this is GCC specific.  

You would need to research other compiler variants potentially or for the else case simply throw a `#pragma error` indicating that the compiler isn't supported. 

I would also suggest merely as an optimization to consider another preprocessor macro that users could set if concurrency isn't needed to optimize these functions so that the atomic operations are omitted in favor of non-atomics.

**Comment by ladislav-zezula** [comment]
> I would also suggest merely as an optimization to consider another preprocessor macro that users could set if concurrency isn't needed to optimize these functions so that the atomic operations are omitted in favor of non-atomics.

This usually leads to more complicated building. Under Win+Lin+Mac, these interlocked operations only take one CPU instruction anyway.

Final proposal is in the branch. If you don't find any more issues, I'll merge them to master.

**Comment by ladislav-zezula** [comment]
Merged and closed.
