### ISSUE TITLE
C++ only feature added to CascPort.h

### ISSUE THREAD

**Issue by nvs** [ladislav-zezula/CascLib#181]
Commit https://github.com/ladislav-zezula/CascLib/commit/0f7aeeca52f1f4f9311efde4b31ebb669ed08f25 introduces the C++ reference operator in CascPort.h, which cannot be used in C and prevents compiling.

```
gcc -O2 -fPIC -c src/test.c -o src/test.o
In file included from /usr/include/CascLib.h:23,
                 from src/test.c:2:

/usr/include/CascPort.h:326:45: error: expected ‘;’, ‘,’ or ‘)’ before ‘&’ token
  326 | inline DWORD CascInterlockedIncrement(DWORD & Value)
      |                                             ^
/usr/include/CascPort.h:338:45: error: expected ‘;’, ‘,’ or ‘)’ before ‘&’ token
  338 | inline DWORD CascInterlockedDecrement(DWORD & Value)
      |                                             ^

```
https://github.com/ladislav-zezula/CascLib/blob/d5c2cba5241746f27c6254d7b4d4f128e8c53a76/src/CascPort.h#L324-L347

**Comment by ladislav-zezula** [comment]
Fixed in commit https://github.com/ladislav-zezula/CascLib/commit/ec893b1bf56484a4eaf45fbc6a3ad6b832c5158c.

Could you please explain your use case to me? I'd particularly like to know why C-only code is needed in 2020.

**Comment by nvs** [comment]
I'm using C in providing Lua bindings to StormLib ([lua-stormlib]) and CascLib ([lua-casclib]). Warcraft III currently makes use of both storage types, and introduced Lua as a scripting language. I wanted a Lua centric development process.

 Is C absolutely necessary for this task? No. But I saw what looked to be a C API with the libraries you develop, and I thought, why not? I like C, and I don't see anything wrong with it in 2020.

Anyways, thanks for addressing the issue. I'll close this as resolved.

[lua-stormlib]: https://github.com/nvs/lua-stormlib
[lua-casclib]: https://github.com/nvs/lua-casclib
