### ISSUE TITLE
Encryption key prompt issue

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#186]
Sorry, this isn't so much an issue with CascLib as with the CascView application. I wasn't sure where to report that.

CascView may need an option to "skip files where no encryption key exists". 

In Shadowlands Blizzard have taken to using a large number of different encryption keys, and now when I try to extract the unnamed files from FILE_DATA_ID it keeps asking me for encryption keys - hundreds and hundreds of times, in fact, which makes it almosty unusable for this function.

Other than that your application (and CascLib) still work fine for Shadowlands, so thank you :)

**Comment by ladislav-zezula** [comment]
Try this:
In the extraction dialog, there are three options at the bottom:

* Show error and stop extracting
* Extract as much as possible, fill gaps with zeros
* Delete the local file and continue extracting

I am gonna change the text on the third option, but that's the option you need. If set, CascView will ignore ANY file that could not be extracted, deletes local (incomplete) file and silently goes to the next file.

**Comment by WainPetopia** [comment]
Thanks :) But I already use that option all the time, but it was still prompting me for the key.

**Comment by ladislav-zezula** [comment]
Ok. Try the newest version. There were some malfunctions, I fixed them. Hopefully.

**Comment by WainPetopia** [comment]
thanks :)

**Comment by ladislav-zezula** [comment]
Try this build: http://www.zezula.net/cascview_wain.zip

**Comment by WainPetopia** [comment]
Thanks. I'll try it now. BTW, I just checked in a huge pile of keys from wow.tools. As you can see, in Shadowlands Blizzard are adding insane numbers of new keys, often one key for file. I'm not sure if you might want to implement them a different way long term or if you're happy with your current system

**Comment by WainPetopia** [comment]
One new bug (minor): if I set the location of my listfile in the options then hit ok, it warns me that it can't find the listfile "" and asks me if I want to proceed anyway. It seems to work though, so it's saving the right file

**Comment by WainPetopia** [comment]
It worked though, and skipped all the files without keys. Thanks :)

**Comment by ladislav-zezula** [comment]
I'll check the bug and also rebuild CascView with the new keys you added.

**Comment by ladislav-zezula** [comment]
> One new bug (minor): if I set the location of my listfile in the options then hit ok,
> it warns me that it can't find the listfile ""

Could you please exactly describe the steps? I can't seem to be able to introduce the bug.

**Comment by WainPetopia** [comment]
Sorry it took me so long to respond. It seems to be fixed. Thank you! :)

And I've incorporated the latest CascLib into WMV and it's running fine. So thanks for that too :)
