### ISSUE TITLE
Linux casc + stormlib: Double definition of GetLastError() 

### ISSUE THREAD

**Issue by Sweepi** [ladislav-zezula/CascLib#188]
Not a real issue, but somehow still a showstopper:
Both stormlib and casclib implement 
GetLastError()
SetLastError()
on Linux, therefore projects which use both libs (like HiveWe) do not link on Linux.

**Comment by herrvigg** [comment]
Namespaces could solve this problem.
In general i dislike such functions a lot because they store the error as a state which is much prone to bugs.
Error codes should rather be returned on function call and never stored, imo it's a very bad coding practice.

**Comment by herrvigg** [comment]
When i say "bad practice", i don't mean this for CascLib. I'm aware this comes originally from very old school Windows API... 😓
But it should be discouraged.

**Comment by ladislav-zezula** [comment]
> I'm aware this comes originally from very old school Windows API... 

No. It actually comes from even older C API. It's nothing more than masked `errno`.

I (hopefully) solved the problem by replacing SetLastError/GetLastError by SetCascError/GetCascError. Many Linux people will have to rebuild their code tho; here is the change in separate branch:
https://github.com/ladislav-zezula/CascLib/tree/NoSetLastError

Please, try if it this solves the problem for you.
