### ISSUE TITLE
Suggestion: read tact keys from a spreadsheet or list of string pairs

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#190]
It's getting very time-consuming to update the CascDecrypt file, because there are so many tact keys being added. And most of the new ones don't have IDs or a defined sort order, so when they are added to wow.tools it's hard to even be sure which are the new ones. Plus, after all that you have to convert the strings to arrays of hex values before adding them.

Would it be possible to change CascLib to get all its keys from a separate spreadsheet, or list of tact name / key pairs (strings), and convert them to arrays in your code? Then we could just import a new list each time and just replace the old one, rather than update it. It hopefully shouldn't be hard since you already have code to read custom keys from a csv file.

Martin told me that WoW.tools exports them using this URL: https://wow.tools/api.php?type=tactkeys
The format is: lookup<space>key\n
You might be able to update it automatically from that. :)

And a readable list of current keys is here: https://wow.tools/dbc/tactkey.php

Thanks :)

**Comment by ladislav-zezula** [comment]
Does the list at https://wow.tools/api.php?type=tactkeys contain all the keys?

I'll make an auto-downloader for TACT keys, but it will not be part of CascLib, but rather a feature of CascView. Can also make an auto-updater of the CascDecrypt source file.

**Comment by ladislav-zezula** [comment]
Step 1) https://github.com/ladislav-zezula/CascLib/tree/ExportImportKeys

**Comment by WainPetopia** [comment]
Sorry I didn’t reply sooner!

Yes, Martin’s list of tact keys is (and will continue to be) the most complete available. The wowdev.wiki lists are actually updated from his (but not as quickly). So it would be good to use his source. 

Thanks for looking into this :) it seems that Blizzard are using more and more keys for things and it’s going to be harder and harder to keep updating that file manually.

**Comment by ladislav-zezula** [comment]
1) Download testing version of CascView from here: http://www.zezula.net/download/cascview_en_wain.zip
2) There is no new UI for the key server, it is only in the config. If you run and exit CascView, it will be written into the "KeyServer" variable in the CascView.ini file.
3) When opening ANY storage, the opening worker thread now does "Downloading TACT keys".

Check the version out. When the feature settles down, I'll add an UI for configuring key server.

**Comment by WainPetopia** [comment]
Thanks! I’ll try it out. 

How will things work for CascLib? Will it continue to need a hardcoded list?

**Comment by ladislav-zezula** [comment]
> How will things work for CascLib? Will it continue to need a hardcoded list?
Both ways. The hard coded list remains there (because there's more storages than just WoW). You can use `CascImportKeysFromFile` or `CascImportKeysFromString` to add a list of keys with format equal to the one downloaded from the key server API.

**Comment by WainPetopia** [comment]
Fair enough. Sorry, I thought wow.tools actually listed all tact keys, but it apparently only has the WoW ones. So the rest at least have to be hardcoded. 

Is there any chance of making that file easier to update by making it an array with two strings, rather than a string and an array of hex integers? It would be much easier to copy data from wowdev.wiki then.

**Comment by WainPetopia** [comment]
Martin is fine with you regularly downloading his list, but warns you should probably cache the previous copy for times when it's down, but you're probably doing that anyway :)

**Comment by ladislav-zezula** [comment]
> Is there any chance of making that file easier to update by making it an array with two strings, rather than a string and an array of hex integers? It would be much easier to copy data from wowdev.wiki then.

Sure, will do.

> Martin is fine with you regularly downloading his list, but warns you should probably cache the previous copy for times when it's down, but you're probably doing that anyway :)

At the moment, CascView only downloads the file once per run. Aka if you open a storage, it will load the list and keep it for the run time. On next run, it will download it again.

If there is an intelligent way to find out the last time when it was updated, let me know.

**Comment by WainPetopia** [comment]
> If there is an intelligent way to find out the last time when it was updated, let me know.
Not currently. For now it's probably best to just download and update it every time, but use a cached version if his site isn't responding

**Comment by WainPetopia** [comment]
Your new version of CascView works for me, by the way, thank you! :)
