### ISSUE TITLE
Changes in latest 9.0 build prevent reading

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#192]
This is just a heads up, because there's no fix yet...

CascLib can't open the latest WoW 9.0.1 build (34902), nor can most other products that read game files.

I don't think a full description of the issue has been made yet, but Martin Benjamins mentioned it on Twitter:
https://twitter.com/Marlamin/status/1275970793881600010

> "There are some mildly interesting file system format changes this patch that might indicate some further attempts at saving disk space by saving patch files opposed to full files inside local archives."

I hope the fix doesn't turn out to be too hard. :/

**Comment by WainPetopia** [comment]
Ignore for now.. this could be a temporary bug rather than an intended change. Sorry.

**Comment by ladislav-zezula** [comment]
Sure, if you detect anything new (and permanent :-)), let me know.
