### ISSUE TITLE
CascView - "not enough memory resources are available" with experimental version

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#193]
An error just started in the experimental version of CascView - the version that downloads Casc Keys from wow.tools.

When I try to open WoW (any version) with the experimental CascView it gives the error:
> Failed to open storage <path>.
> Not enough memory resources are available to process this command.

The game itself is working for me. I have run and played the live and beta versions. And I can open it in Wowmodelviewer and your public release version of CascView.

The error seems to happen soon after it says it's downloading the latest Casc Keys. Martin said a bunch of new Casc Keys have been added recently, so maybe more memory needs to be allocated for them?

Thanks :)

**Comment by ladislav-zezula** [comment]
Fixed in commit https://github.com/ladislav-zezula/CascLib/commit/50b9df687052cb63acc3735a798e339d9ad42cd7

**Comment by WainPetopia** [comment]
Thanks! :)
