### ISSUE TITLE
Open Remote TACT Storage on Linux

### ISSUE THREAD

**Issue by Luzifix** [ladislav-zezula/CascLib#196]
Hello is there a possibility to use another HTTP client to be able use remote storage on linux as well?

https://github.com/ladislav-zezula/CascLib/blob/c1d6d9cd4ddd2b5ec975348166171d571198278e/src/common/FileStream.cpp#L748

**Comment by ladislav-zezula** [comment]
It would require someone to fill-in the HTTP part for Linux. Unfortunately, I am not a Linux expert.

**Comment by ladislav-zezula** [comment]
Network part of the CascLib was re-implemented using sockets. Also I added support for Ribbit protocol.
https://github.com/ladislav-zezula/CascLib/pull/198
