### ISSUE TITLE
Linux build failure

### ISSUE THREAD

**Issue by skarnproject** [ladislav-zezula/CascLib#212]
https://github.com/ladislav-zezula/CascLib/blob/7369699afb4f22da2cd759f1a1abcf1a48b87ea2/src/CascLib.h#L384

It seems the windows specific LPDWORD type was not forwarded through CASCPort.h on Linux, unable to build CASCLib on Clang under Ubuntu. (Custom CDN branch only)

**Comment by ladislav-zezula** [comment]
Fixed in commit https://github.com/ladislav-zezula/CascLib/commit/9f2534a9e72e2e2d7b42e8fa46ed2b9f3daf6bf7

**Comment by skarnproject** [comment]
Thanks!
