### ISSUE TITLE
Redefinition of symbols

### ISSUE THREAD

**Issue by stijn-ucrowds** [ladislav-zezula/CascLib#215]
The `#include <ws2tcpip.h>` header include in CascPort.h causes a long list of errors related to redefinitons, as an example:
```In file included from C:\Users\User\CMakeBuilds\6f9bf42a-cb87-4d4e-90ef-12b7d9f9df67\build\x64-Clang-Release\vcpkg_installed\x64-windows\include\CascLib.h:23:
  In file included from C:\Users\User\CMakeBuilds\6f9bf42a-cb87-4d4e-90ef-12b7d9f9df67\build\x64-Clang-Release\vcpkg_installed\x64-windows\include/CascPort.h:43:
  In file included from C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um\ws2tcpip.h:43:
  In file included from C:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um\winsock2.h:116:
C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared\ws2def.h(240,16): error : redefinition of 'sockaddr'
  typedef struct sockaddr {
                 ^
  C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um\winsock.h(482,8): note: previous definition is here
  struct sockaddr {
         ^
```
Commenting out the include solves the issue.

**Comment by ladislav-zezula** [comment]
I tried to install the SDK 22000 into Visual Studio 2019 and it still compiles fine.
Could you please describe your building environment?

**Comment by stijn-ucrowds** [comment]
The issue is in my [HiveWE](https://github.com/stijnherfst/HiveWE) project. I think it might specifically be due to also including Stormlib. Is the ws2tcpip header needed and/or could it perhaps be moved to a .cpp file instead?

**Comment by ladislav-zezula** [comment]
It is needed. Could you try to use the https://github.com/ladislav-zezula/CascLib/tree/LZ_WinsockConflict branch in your project instead?

**Comment by TheNitesWhoSay** [comment]
This problem occurs for me when
<Windows.h> is included before CascLib.h (and thus included before <ws2tcpip.h>)

Here's a bare-minimum reproduction/demonstration of the problem: https://godbolt.org/z/hca59noo1

I don't see a very elegant solution for this, but you can work around it by ensuring CascLib.h is the very first header you're including in a given file.

**Comment by ladislav-zezula** [comment]
But `windows.h` **is** included before `ws2tcpip.h` in Casclib itself.

**Comment by TheNitesWhoSay** [comment]
o, perhaps then it's only when a non-lean windows.h (or some other problematic windows header) was included before CascLib.h e.g. https://godbolt.org/z/7rbK5n5nP

**Comment by ladislav-zezula** [comment]
I see loads of errors when I remove `WIN32_LEAN_AND_MEAN` from CascPort.h.
And yes, I do have `WIN32_LEAN_AND_MEAN` in CascView.h
I'll try to figure something out.

**Comment by ladislav-zezula** [comment]
Ok, I tried this:

* Removed `#define WIN32_LEAN_AND_MEAN` in `CascPort.h`
* Replaced `#include <windows.h>` by `#include <winsock2.h>` in `CascPort.h`

The library builds fine, and it no longer matters whether projects have WIN32_LEAN_AND_MEAN or not.
But then, every project built with it must also include `<winsock2.h>` instead of `<windows.h>`. 

Personally I don't like this solution. This will break every single project that uses CascLib. I think if `CascLib.h` will just require WIN32_LEAN_AND_MEAN, it will be enough.

**Comment by ladislav-zezula** [comment]
Please, try this branch: https://github.com/ladislav-zezula/CascLib/tree/LZ_WinsockHeadersProblem

**Comment by TheNitesWhoSay** [comment]
I can get it working for me in a couple ways regardless - but anyways, your warning does show up, though some people might have trouble seeing it -- someone with the discipline to keep a clean warning list and scroll to the top of the output window when debugging a problem like this will see it, though it's also at the bottom of the error list after the other 100 errors/warnings.

A more difficult solution, if you were so inclined, might be to only have the header included in CascLib's cpp files and not in the library headers. e.g. use void* in place of SOCKET in CASC_SOCKET/Sockets.h and have Sockets.cpp #include <ws2tcpip.h> if CASCLIB_PLATFORM_WINDOWS is defined

**Comment by ladislav-zezula** [comment]
> A more difficult solution, if you were so inclined, might be to only have the header included in CascLib's cpp files and not in the 

Yeah, that's probably the best one. I abstracted the SOCKET type into an opaque type of HANDLE. The problematic `#include <ws2tcpip.h>` is now hidden inside `Sockets.cpp`. You can try this variant out.

**Comment by TheNitesWhoSay** [comment]
Works perfect for me 👍

**Comment by ladislav-zezula** [comment]
Ok then. https://github.com/ladislav-zezula/CascLib/pull/236 merged.
