### ISSUE TITLE
Changes to CASC in this build

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#221]
As of the new DF build (45779) CascView isn't assigning names to files.

I asked on the Discord and was told:

> Max: WoW has VFS support
> Max: I straight up assume Ladik isn’t ignoring VFS tags in BuildConfig
> Zee: Just use wow root handler still works

I don't know if that helps, but I hope it does!

Thanks :)

**Comment by ladislav-zezula** [comment]
I can confirm that current build of CascView parses the wow_beta game's TVFS well. However, it does assume that TVFS contains file names, as it did in Warcraft III. WoW doesn't have the names there, so I need to adapt it to the new situation.

**Comment by ladislav-zezula** [comment]
This is the list of file names that I extracted from the TVFS root manifest (see below). Note that these are actual filenames, not a text representations of an MD5. They are sorted by the "directory" (000000020000, 000000040000, 000000100000), then by the rest of the hexa string. The hexa string has odd number of digits (39).

My speculations:
* Could the number before colon be a locale number?
* Could the value after the colon be MD5 + extra 7 digits?

Anyway, we need to find the mapping between the current CSV listfile and these file names.

```
.root
000000020000:000C472 F02BA924C604A670B253AA02DBCD9441
000000020000:000C481FFBE6550527E0984CB649F176216F332
000000040000:00000015350F9647B58D08B3381B5F04A96A405
000000040000:0002178A45AF2A049ED7E1A676FDCDD4A27CFE5
...
000000040000:0048579779EF80D6B24E56AFC50C95C5805211C
000000040000:004857992A60E6E7BDB3DC27CFAE77B8BA7F41D
000000100000:0000001538028FF950A2671C408641D02FEBD2C
000000100000:0002178AC3AA5ADEC196CA8028BBCC96767CA31
...
000000100000:0047C78332C9E22E17163506C9FE7926BE0C51E
000000100000:0047C784805CCE4E8C1708ED90B51B3DCA495DE
000000140000:0014C1D031C7EB6840559501D1EE663E9CA8F68
000000140000:0014C1D6EC96FCC910353F2D6F7ADB8DA45977C
000000140000:001F05A6C0767242B9A5E9300B7783FF76B63F2
000000200000:0000001579D37A4DC9E58FD07A2BF654B96736C
000000200000:0002178AAC0D1502F4D80E31D33D902C199AC3B
...
000000200000:0048254ABA2CE7A5FC194C890982CFAC8168F76
000000200000:0048254BB5BE2823E9B14EAD725D6C1EA399296
000000240000:0004286CEC2BDD6D0B6172FB66B015BA40EF35A
000000240000:00042880EFA42024541C3A902AFE6F9FB691DF3
000000240000:0004288108EF27B8CC7D24F61CF76E8E42CF289
000000240000:000428821CB6F9C09CB10982C69FFEDECF1DBA3
000000240000:0004288DB7481FBBD361A681872E3114B76542D
000000240000:0004289A2F55D9D625068EABD6B3080EB0088C6
000000240000:000428EAD0CB59F9F07FD362082A46D12EDC6EA
000000240000:000955D1AC6C8E308E239E29B06466B7B9C5221
000000240000:000955D7DE85034BBAED98F564A45005403732E
000000240000:001F0914BB4ABDADC7A4CFD1A7115B0F3513059
000000240000:001F189418D4362FFFD6B91DA69365BE4ABB3F1
000000300000:0003DA6476ABA2640B1E652BF3BED7A66FDDFFF
000000300000:0004210A80B8204DA9225E2E1A7B00179D638C0
...
000000300000:001F072C608B3387A22A19F9350513163222E1B
000000300000:0030B82A59C0B6F50FEA61B6134DF43ADE17FD9
000000340000:00042AEF8F53FF8232CF76F9DE452EAF9BDA4EC
000000400000:00000015C1CA8A0D8007EA81E73163D8812AD38
000000400000:0002007A6677A05EA2FD05E23C4CA6F3977E1A5
```

**Comment by ladislav-zezula** [comment]
I'll temporarily disabled using TVFS for World of Warcraft games. It appears to work as usually, although it's gonna be tenporary only.
https://github.com/ladislav-zezula/CascLib/pull/222

**Comment by Marlamin** [comment]
The filenames are hex encoded strings of 4 bytes of FileDataID (uint32) and then the ckey/content hash/MD5 of the file minus 1 character at the end (huh?).

e.g. `000C472F 02BA924C604A670B253AA02DBCD9441`  corresponds to FileDataID 804655 and ckey `02ba924c604a670b253aa02dbcd9441c` which is used for the file `interface/framexml/localization.lua`.

**Comment by WainPetopia** [comment]
Thanks for explaining it, Martin! And thanks for looking at it Ladik! :)

**Comment by Marlamin** [comment]
Minor update on folder filenames, first 8 characters are LocaleFlags, remaining 4 characters are (partial) ContentFlags.

There are some new flags specifically for the install manifest files, I've updated [the list on wiki](https://wowdev.wiki/TACT#Root) with (unverified) names.

_Thanks Tom for figuring out which parts are locale/content flags!_

**Comment by ladislav-zezula** [comment]
Thanks for explanation of the meaning of the values in TVFS.

I prepared build of CascView, based on the current master branch of CascLib. It reads meaningful names from TVFS, but when it encounters WoW cryptic name, it reparses back to the original ROOT folder. We shall see what tomorrow brings.
