### ISSUE TITLE
WoW TVFS: FiledataIDs

### ISSUE THREAD

**Issue by Deamon87** [ladislav-zezula/CascLib#224]
`CASC_FILE_TREE::FileDataIds` field are essential for reading from local CASC by FileDataId now that `wowt` and `wow_beta` have this thing.

Basically TRootHandler_TVFS class doesnt fill this array with data. Thus making it impossible to read by FileDataId by calling `CascReadFile`

PS: `!CheckForWorldOfWarcraft(hs)` check is commented out as of latest commit in master branch: https://github.com/ladislav-zezula/CascLib/blob/master/src/CascOpenStorage.cpp#L892

**Comment by ladislav-zezula** [comment]
> !CheckForWorldOfWarcraft(hs) check is commented out as of latest commit in master branch: https://github.com/ladislav-zezula/CascLib/blob/master/src/CascOpenStorage.cpp#L892

This is because when the TVFS finds our the generic WoW name, it returns ERROR_REPARSE_ROOT and the common root handle takes over.

**Comment by Marlamin** [comment]
Smells like they fixed that last missing character of the contenthash maybe?

**Comment by Deamon87** [comment]
Thanks a lot :). I will inform if something new about this stuff appears

**Comment by ladislav-zezula** [comment]
I experimented with the WoW TVFS a bit, but it is significantly slower than the legacy ROOT. For now, the support is present in CascLib, but it's comented out via an `#ifndef` in [CascRootFile_TVFS.cpp](https://github.com/ladislav-zezula/CascLib/blob/19e2a559c28b2bc9b3db3b5f9ffa840a24911e0e/src/CascRootFile_TVFS.cpp#L743).
