### ISSUE TITLE
can't open overwatch casc

### ISSUE THREAD

**Issue by nongnoobjung** [ladislav-zezula/CascLib#23]
can't open overwatch casc

to force install overwatch
battle.net.exe --switcherall --install --game=prometheus --installlocale=enUS --installregion=US --torrentinstall

**Comment by ladislav-zezula** [comment]
Installation works so far, I'll look at it.

**Comment by Cohmervac** [comment]
@ladislav-zezula 
I just force installed Overwatch 
(if you have trouble, revert the battle.net launcher to the previous version just before they patched it)
I can not extract the files.
Tried it with game storage, got this...
https://i.gyazo.com/773f8731dd278acebaff3ace275b5b0a.png
Tried it with open storage, got this...
https://i.gyazo.com/84693e69c4b7e0f085e6b39074afcdeb.png
Please do your best to get it working for Overwatch! I REALLY want to extract the models!

**Comment by ladislav-zezula** [comment]
Cohmervac: Working on it.

**Comment by swqsldz** [comment]
I extract the rootfile, but i found it's a textfile(start with #MD5, i had thought it's the signature )
Here is the rootfile

#MD5|CHUNK_ID|FILENAME|INSTALLPATH
FE3AD8A77EEF77B383DF4929AED816FD|0|RetailClient/GameClientApp.exe|GameClientApp.exe
5EDDEFECA544B6472C5CD52BE63BC02F|0|RetailClient/Overwatch Launcher.exe|Overwatch Launcher.exe
6DE09F0A67F33F874F2DD8E2AA3B7AAC|0|RetailClient/ca-bundle.crt|ca-bundle.crt
99FE9EB6A4BB20209202F8C7884859D9|0|RetailClient/ortp_x64.dll|ortp_x64.dll
........

**Comment by Cohmervac** [comment]
@ladislav-zezula 
So, do you have a work-in-progress fix available for download? I'm not good with GitHub, not sure where the exe downloads are.
Sorry, no rush, I just want to do something today.

**Comment by ladislav-zezula** [comment]
There is no EXE download here. The preliminary version of CascView can already extract files, but can't give them names yet.

**Comment by Cohmervac** [comment]
@ladislav-zezula 
From overwatch? Also, can't give them names? I think I follow, but I can still get files out, right?
I'm going to try exacting crap again.

**Comment by Cohmervac** [comment]
@ladislav-zezula 
Ah, I see, I CAN get the files, but none of them are really identifiable.

**Comment by Cohmervac** [comment]
@ladislav-zezula 
Extracting gives me an error, probably due to the naming issues.

**Comment by ladislav-zezula** [comment]
Ok, some basic functionalty is done; however, until I (or someone) don't figire out the name -> encoding key relationship, both CascLib and CascView will only extract files by their MD5.
