### ISSUE TITLE
Diablo 4 support

### ISSUE THREAD

**Issue by Chuanhsing** [ladislav-zezula/CascLib#232]
Diablo 4 Beta pre-download online. 

it's missing file names and encrypted key 74708D4551CAE93F value.

**Comment by ladislav-zezula** [comment]
Do you have an installer of it?

**Comment by Chuanhsing** [comment]
nope, but you can pre-download beta if you bought the game already. https://news.blizzard.com/en-us/diablo4/23916442/your-guide-to-the-diablo-iv-open-beta

**Comment by ladislav-zezula** [comment]
I haven't decided yet if I buy the game or not.

In the meantime, could you extract the file "ROOT" from the storage and put it here for download? The ROOT file is the one that contains translation from file names to CKeys (MD5's).

As for the encrytion key, Blizzard often encrypts data that are not supposed to be readable until a game release. There's nothing we can do with it.

**Comment by Chuanhsing** [comment]
![image](https://user-images.githubusercontent.com/1129924/225829065-6d405127-aea4-457e-aeef-31897afa34d0.png)
ROOT file is missing[](url)

build.info
```
Branch!STRING:0|Active!DEC:1|Build Key!HEX:16|CDN Key!HEX:16|Install Key!HEX:16|IM Size!DEC:4|CDN Path!STRING:0|CDN Hosts!STRING:0|CDN Servers!STRING:0|Tags!STRING:0|Armadillo!STRING:0|Last Activated!STRING:0|Version!STRING:0
kr|1|a877f86a8cd1c1543ebf54bcb0df58b6|b3723dfe2965966b39ff72e97838f4f9|d3b6a20efe685a0ebaa32a7c535af8ee||tpr/fenris|level3.blizzard.com blzddistkr1-a.akamaihd.net kr.cdn.blizzard.com blizzard.gcdn.cloudn.co.kr|http://blizzard.gcdn.cloudn.co.kr/?maxhosts=4 http://blzddistkr1-a.akamaihd.net/?fallback=1&maxhosts=4 http://kr.cdn.blizzard.com/?maxhosts=4 http://level3.blizzard.com/?maxhosts=4 https://blizzard.gcdn.cloudn.co.kr/?fallback=1&maxhosts=4 https://blzddistkr1-a.akamaihd.net/?fallback=1&maxhosts=4 https://kr.cdn.blizzard.com/?fallback=1&maxhosts=4 https://level3.ssl.blizzard.com/?fallback=1&maxhosts=4|Windows KR? acct-TWN? geoip-TW? zhTW speech?:Windows KR? acct-TWN? geoip-TW? zhTW text?|||0.8.0.39517
```

I will check this after 10 hours that beta testing is opened.

**Comment by Chuanhsing** [comment]
there is an open beta for all player next week, even if you dont buy the game.
**The Open Beta begins March 24 at 9 a.m. PDT and concludes March 27 at 12 p.m. PDT.**

Or I could upload all file to somewhere, but I tried to send a email to your ladik@ mail address, but received **421 Unexpected failure, please try later**.

**Comment by Shavalyoth** [comment]
Seems to work after modifying CASC Explorer.
![Untitled](https://user-images.githubusercontent.com/104050834/225832269-ee0c326f-0d9c-46a9-8b50-5293621d93f9.png)

**Comment by Chuanhsing** [comment]
@Shavalyoth could you share how your modified CASC Explorer files?

**Comment by Chuanhsing** [comment]
Diablo IV Beta TACT: fenrisb

**Comment by Chuanhsing** [comment]
Could I ask CASC Lib questions here? In CascView (1.9MB), it can find all Diablo 3 listfile, how does this work? Download list file instantly or get listfile information from TACT/Ribbit?

**Comment by Chuanhsing** [comment]
If you grab the [Battle.net Installer Github project](https://github.com/barncastle/Battle.Net-Installer), open a terminal window or command prompt, go to the directory you put bnet installer in and use the following command:

`BNetInstaller.exe -prod fenrisb -lang enus -dir "(where you want to install)"`

You can kinda sorta totally download the D4 Beta.

**Comment by bonesoul** [comment]
@Shavalyoth any chances you can share your changes?

**Comment by s-master** [comment]
Would love to extract the music from the game <3

**Comment by Chuanhsing** [comment]
@bonesoul @s-master https://github.com/WoW-Tools/CASCExplorer/releases CASCExplorer update Diablo IV Beta support

**Comment by s-master** [comment]
i know it's totally off-topic, but maybe someone come across this post and tried the same as I.
i could extract the music files with cascexplorer from the d4 beta and then convert/unpack them to .ogg
but all the 1000 music files are kinda useless. its music yes, but kinda incomplete. as if they are combined in-game from different files to make it a "soundtrack". it's like its only one channel or something. 
sorry for my bad english, i can't even explain it right in my native language.

**Comment by ladislav-zezula** [comment]
> Or I could upload all file to somewhere, but I tried to send a email to your ladik@ mail address,

Please, ZIP the files from the game folder (not subfolders). Then, Battle.net client should be able to download rest of the files for me.

**Comment by Chuanhsing** [comment]
[[](url)](https://poedb.tw/dls/Diablo%20IV%20-%20Beta.zip)
55.4MB

**Comment by ladislav-zezula** [comment]
> Could I ask CASC Lib questions here? In CascView (1.9MB), it can find all Diablo 3 listfile, how does this work? Download list file instantly or get listfile information from TACT/Ribbit?

Diablo III is a TACT game. CascLib extracts names from the ROOT file and serves them in a user-friendly way.

**Comment by ladislav-zezula** [comment]
> [](https://poedb.tw/dls/Diablo%20IV%20-%20Beta.zip) 55.4MB

Thanks. I downloaded the pack and will also use the BNet installer. I'll check the files and fix CascLib as necessary.

At the very least, Diablo IV Beta is not in the list of Blizzard games in the current version of CascView, I'll fix it.

**Comment by ladislav-zezula** [comment]
Diablo IV uses TVFS-style ROOT file, which is supported by CascLib / CascView. There are no changes needed. I'll do some slight fixes, but it works as it is.

**Comment by ladislav-zezula** [comment]
There is a name conflict between files and reparse points in the Diablo IV TVFS root file.

* A file named `Base` (CKey `d2 8a 21 30 bf 6c 92 86 e2 16 da 15 9c 6b 34 f2`, content size `0x00250890`).
* Reparse point files starting with `base`, like `base:ComplexTypeDescriptorSizes.dat` (CKey `98 eb cf f1 45 1f 25 d3 b4 52 09 f1 6f fd ae aa`, content size `0x000040dc`). 

This is something that CascLib doesn't handle well, and I need to figure out how to do it properly.

**Comment by ladislav-zezula** [comment]
Preliminary support for Diablo IV is in the branch: https://github.com/ladislav-zezula/CascLib/tree/LZ_CascLib_Diablo4
Beta version of CascView, built with this version is here: http://www.zezula.net/download/cascview_en_diablo4.zip

**Comment by ladislav-zezula** [comment]
https://github.com/ladislav-zezula/CascLib/pull/233

**Comment by ladislav-zezula** [comment]
CascView rebuilt and uploaded to my web page.

**Comment by nitrotech7** [comment]
> 

hey, how did u convert those .wsb music files to ogg?

**Comment by nitrotech7** [comment]
> CascView rebuilt and uploaded to my web page.

is 2.4.0.253 the latest version? i just dl it but i dont see any meaningful files (ie. audio, videos). i mean i cant use them. some would have the header RIFFåg WAVEfmt but i cant open it in any audio player. is it encrypted or something? am i missing a codec? needs conversion to some other format?
![2023-03-24_233559](https://user-images.githubusercontent.com/53409493/227655695-148ba607-b4ca-4651-bb62-7a2f079a885f.jpg)
![2023-03-24_233803](https://user-images.githubusercontent.com/53409493/227655696-cd59b759-31f0-4040-86e1-9eb7739d9603.jpg)

**Comment by nitrotech7** [comment]
ok i was able to convert audio files (extracted with either Ladik's Casc Viewer or CASC Explorer) to ogg with this tool https://github.com/hcs64/ww2ogg
and then running revorb on the output to fix it up
![image](https://user-images.githubusercontent.com/53409493/227659615-4fcb9b5b-eacd-473d-b548-655ebc674688.png)

**Comment by bonesoul** [comment]
anyone be able to extract stl files?

**Comment by ladislav-zezula** [comment]
> hey, how did u convert those .wsb music files to ogg?

I would like to make something clear. I don't deal with the content of files, mostly. CascView ONLY does extracting files from the storage. It is not in my powers to deal with all game formats. I leave that to the game-associated communities.

The only exception is the image viewer, which, for some of the game formats, is able to display the image. However, I did not do any research about the format of the Diablo 4 images.
