### ISSUE TITLE
Suggestion: Exported file names in decimal instead of hex

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#237]
This is just a suggestion for a feature change for CascView.

Currrenly, if a file isn't found in listfile then it's assigned a name based on a hexadecimal version of its file ID.

Is it important that it's hexadecimal? If not, could that name be given in decimal instead?

The reason that I ask is that most apps that catalog WoW files (including wow dot tools) present file IDs in a decimal format, so it's much quicker to look up unknown files from CascLib.

It's not a big deal, it just saves me manually having to convert each file from hex to dec before looking them up.

Thanks :)

**Comment by ladislav-zezula** [comment]
Sure it would be possible, we just need to agree on something meaningful.

Currently, if a file data ID is found:

* CascView constructs a a virtual folder (`FILE_DATA_ID\\00080000-0008FFFF\\`)
* Then, the fake file name ('FILE%08X.dat') is used.

The first part can be decimal or hexadecimal, the second is always hexa-decimal.

So, I need to know:

* Virtual Folder: Yes/No?
* Virtual Folder: If yes, what would be the best form?
* Virtual file name: What form? Would the setting is form of a C format string help?

Please, send me a screenshot of a tool, that you mention. So I can get an imagination about what you would like.

**Comment by ladislav-zezula** [comment]
This is a test build that can switch the display of the file ID to decimal. Let me know if that works for you:
http://www.zezula.net/download/cascview_en_decimal_fileid.zip

1. Run CascView and exit it.
2. Open the INI file: `c:\Users\%USERNAME%\AppData\Roaming\CascView.ini` 
3. Locate the variable `DataIdDecimal` and set it to `true`
4. This is the result:

![obrazek](https://github.com/ladislav-zezula/CascLib/assets/3244359/f122ee49-2d1d-4197-9c84-85a3c8a727dc)

**Comment by WainPetopia** [comment]
I'm so sorry I didn't reply! I didn't see any notifications for this.

Thanks so much for looking at it so quickly! I'll go test it now :)

**Comment by WainPetopia** [comment]
I did what you said, edited the .ini, and relaunched the program and it ran. 

But as soon as I select a game version it closes, with no error message. I tried the regular game and the PTR.

**Comment by ladislav-zezula** [comment]
I rebuilt CascView from the latest sources. Please, download and retry.
If it crashes again, try to backup the existing CascView.ini (`c:\Users\%USERNAME%\AppData\Roaming\CascView.ini`) and run CascView again.
If it still crashes, then please, send me your CascView.ini, if possible.

**Comment by WainPetopia** [comment]
Sorry, I'm afraid it's still crashing :(

I downloaded a fresh copy, using the link from your last post. I tried both the x32 and x64 versions.

I deleted the .ini file first, so it created a new one. I didn't modify it, so it was still using the default hex numbering system. I closed the program and reopened it to ensure the .ini file had been saved before proceeding.

But it still closes as soon as I select one of the WoW versions. No error message.

[CascView.ini.txt](https://github.com/ladislav-zezula/CascLib/files/11892820/CascView.ini.txt)

**Comment by WainPetopia** [comment]
Wait... it works if I use the "Open Storage" button and select the game folder, but it crashes if I use the "Game Storage" button to select it. 

In both cases, I select the exact same game version, but one crashes.

I tried setting the option to decimal and that works too (using the Open Storage button).

**Comment by ladislav-zezula** [comment]
Oookey, now we're getting somewhere. I'll see the crash, will look what's wrong.

**Comment by ladislav-zezula** [comment]
Fixed. Please, re-download and try the decimal IDs again
http://www.zezula.net/download/cascview_en_decimal_fileid.zip

**Comment by WainPetopia** [comment]
It works perfectly, thank you!!

I can now look reference files directly between CascView and wow dot tools. It saves me a lot of time :)

I really appreciate all your work 😊

**Comment by ladislav-zezula** [comment]
Oki. Closing the issue now 👍
