### ISSUE TITLE
Weird behavior when opened in online mode if cache directory is inside a local casc storage

### ISSUE THREAD

**Issue by Shauren** [ladislav-zezula/CascLib#238]
Example:
Local casc storage: "D:\World of Warcraft"
remote cache: "D:\World of Warcraft\CascCache"

Attempting to read any file fails
```
Name: DBFilesClient\Achievement.db2
FileDataID: 1260179
```

The reason for this is I believe is a different EKEY value
```
"Local" 7f9344203188ec03df65df16387767fe (when opened casc storage using remote cache in D:\World of Warcraft\CascCache)
Remote: 9c1803860e4308f3c99a05132f618587 (when opened in a completely different directory)
```

Both local storage and remote storages point to the same build, wow 10.1.0.50000 with buildkey `26f9ff71801755f7cfc70519c32e41b5` and cdnkey `84904d5782e063b87455d8312fa800c5`

I believe this part of the code is responsible for this behavior, more specifically build info lookup order, that then causes LoadIndexFiles to take a different code path
https://github.com/ladislav-zezula/CascLib/blob/0d65a1caa6927a440999fe9a341ae6aaccbd5f65/src/CascOpenStorage.cpp#L1388-L1413

Should anything be done about it on casclib side or should applications detect this kind of edge case and protect themselves from it?

Yes, I agree that using remote mode of casclib inside a local storage is dumb but somebody did this and I had to spend a lot of time figuring out why remote mode was not working for that user

**Comment by ladislav-zezula** [comment]
I'll download the exact build and look at it.

**Comment by Shauren** [comment]
db2 files are only partially encrypted (which is why #138 and CASC_OVERCOME_ENCRYPTED are a thing)

**Comment by ladislav-zezula** [comment]
The bug comes from different setting of file locale.

* In local storages, CascLib reads the WoW locale from the `.build.info` file. My own installation contains tag `enUS`, hence the file locale is 0x02 (`CASC_LOCALE_ENUS`)
* In online storage, there is no such tag, so the locale is set to `CASC_LOCALE_ALL`. This causes loading different files in ID range of 801709 to 1260179 and beyond. 

Now the question is what to do with it.

Personally, I would rather set the default file locale to CASC_LOCALE_ALL for all installations. This will lead to CascView showing way more files, but also showing way more unavailable files (those are displayed red in CascView).

Another option would be to deduce the locale mask from the region.

**Comment by Shauren** [comment]
I don't think thats the case for me because the tool that I'm using CascLib in explicitly passes locale to CascOpenStorageEx in both local and remote cases,

this part doesn't apply to me
https://github.com/ladislav-zezula/CascLib/blob/8ec142dffda174e1a5f0deb776d684afb852ff64/src/CascOpenStorage.cpp#L1207-L1214

**Comment by Shauren** [comment]
Yes, thats exactly what happened (it found .build.info)

I don't actually need or want to support having online caches inside a game subdirectory

This issue is more like an observation that many functions inside CascLib think that storage was opened in online mode when it actually was not

#240 is my answer to this situation

**Comment by ladislav-zezula** [comment]
I want to trigger online behavior anytime when a `versions` file is found, which can be in these cases:

* Call to `CheckCascBuildFileExact()` in case when exact path to a `version` file was passed to CascOpenStorageEx
* Call to `CheckCascBuildFileDirs()` discovers a `versions` info in a folder
* Call to `CheckOnlineStorage()` will confirm an online storage (e.g. a folder with `versions`) file

Thus, I am offering you a counter-merge-request: https://github.com/ladislav-zezula/CascLib/pull/241

**Comment by Shauren** [comment]
That also works for me, both our changes ensure that `((dwFeatures & CASC_FEATURE_ONLINE) != 0) == (BuildFileType == CascVersions)`
