### ISSUE TITLE
zezula.net

### ISSUE THREAD

**Issue by ElementShadow** [ladislav-zezula/CascLib#248]
1. wanted to say that contact button via e-mail dont work (and i didnt found any other way to contact you)
2. wanted to ask, if its possible using Casc(or any other software) and replace audio files(want to change dark templar attack sound) in starcraft remastered? and still able to play ladder games?

**Comment by ladislav-zezula** [comment]
> wanted to say that contact button via e-mail dont work (and i didnt found any other way to contact you)

It works for me in Firefox and Chrome. It should open default e-mail client.

> wanted to ask, if its possible using Casc(or any other software) and replace audio files(want to change dark templar attack sound) in starcraft remastered? and still able to play ladder games?

All versions of StarCraft use MPQ format for maps. You need MPQ Editor to edit them.

**Comment by ElementShadow** [comment]
So if i dont use any mail client, i cant send you message? i was thinking you made window to send messages or just mail link -_-)
