### ISSUE TITLE
Casclib fails to extract files on some WoW installations.

### ISSUE THREAD

**Issue by Fabi** [ladislav-zezula/CascLib#249]
Without writing everything down again I'm going to link the issue form TC: https://github.com/TrinityCore/TrinityCore/issues/29102

That's randomly happens on some WoW installations, especially on installations with multiple patch cycles and/or locales.

I didn't debug much but it actually fails at that point when extracting Achievement_Category in this case (pEncodedHeader->EncodedSize is 0):
![image](https://github.com/ladislav-zezula/CascLib/assets/246718/082db349-6da3-4ab5-9d43-7c39ce98922b)

The same issue appears on CascView. That being said, ignoring the ERROR_BAD_FORMAT and let it continue execution will make those files extract just fine.

**Comment by ladislav-zezula** [comment]
Fixed in https://github.com/ladislav-zezula/CascLib/pull/250.
Apparently, sometimes the extra data in the encoded BLTE header are zeroed.
