### ISSUE TITLE
VS 2015 doesn't link for DLL mode

### ISSUE THREAD

**Issue by robpaveza** [ladislav-zezula/CascLib#25]
I had to set the -D versions of the project to link to DLLs.  Also, I get unresolved externals when building:

    1>------ Build started: Project: CascLib, Configuration: DebugAD Win32 ------
      (snip)
    1>  Generating Code...
    1>CascOpenStorage.obj : error LNK2019: unresolved external symbol "int __cdecl Array_Create_(struct _DYNAMIC_ARRAY *,unsigned int,unsigned int)" (?Array_Create_@@YAHPAU_DYNAMIC_ARRAY@@II@Z) referenced in function _CascOpenStorage@12
    1>CascRootFile_Diablo3.obj : error LNK2001: unresolved external symbol "int __cdecl Array_Create_(struct _DYNAMIC_ARRAY *,unsigned int,unsigned int)" (?Array_Create_@@YAHPAU_DYNAMIC_ARRAY@@II@Z)    
    1>CascRootFile_WoW6.obj : error LNK2001: unresolved external symbol "int __cdecl Array_Create_(struct _DYNAMIC_ARRAY *,unsigned int,unsigned int)" (?Array_Create_@@YAHPAU_DYNAMIC_ARRAY@@II@Z)
    1>CascOpenStorage.obj : error LNK2019: unresolved external symbol "void * __cdecl Array_Insert(struct _DYNAMIC_ARRAY *,void const *,unsigned int)" (?Array_Insert@@YAPAXPAU_DYNAMIC_ARRAY@@PBXI@Z) referenced in function "int __cdecl InsertExtraFile(struct _TCascStorage *,char const *,struct _QUERY_KEY *)" (?InsertExtraFile@@YAHPAU_TCascStorage@@PBDPAU_QUERY_KEY@@@Z)
    1>CascRootFile_Diablo3.obj : error LNK2001: unresolved external symbol "void * __cdecl Array_Insert(struct _DYNAMIC_ARRAY *,void const *,unsigned int)" (?Array_Insert@@YAPAXPAU_DYNAMIC_ARRAY@@PBXI@Z)
    1>CascRootFile_WoW6.obj : error LNK2001: unresolved external symbol "void * __cdecl Array_Insert(struct _DYNAMIC_ARRAY *,void const *,unsigned int)" (?Array_Insert@@YAPAXPAU_DYNAMIC_ARRAY@@PBXI@Z)
    1>CascOpenStorage.obj : error LNK2019: unresolved external symbol "void __cdecl Array_Free(struct _DYNAMIC_ARRAY *)" (?Array_Free@@YAXPAU_DYNAMIC_ARRAY@@@Z) referenced in function "struct _TCascStorage * __cdecl FreeCascStorage(struct _TCascStorage *)" (?FreeCascStorage@@YAPAU_TCascStorage@@PAU1@@Z)
    1>CascRootFile_Diablo3.obj : error LNK2001: unresolved external symbol "void __cdecl Array_Free(struct _DYNAMIC_ARRAY *)" (?Array_Free@@YAXPAU_DYNAMIC_ARRAY@@@Z)
    1>CascRootFile_WoW6.obj : error LNK2001: unresolved external symbol "void __cdecl Array_Free(struct _DYNAMIC_ARRAY *)" (?Array_Free@@YAXPAU_DYNAMIC_ARRAY@@@Z)
    1>CascOpenStorage.obj : error LNK2019: unresolved external symbol "int __cdecl RootHandler_CreateOverwatch(struct _TCascStorage *,unsigned char *,unsigned long)" (?RootHandler_CreateOverwatch@@YAHPAU_TCascStorage@@PAEK@Z) referenced in function "int __cdecl LoadRootFile(struct _TCascStorage *,unsigned long)" (?LoadRootFile@@YAHPAU_TCascStorage@@K@Z)
    1>CascReadFile.obj : error LNK2019: unresolved external symbol "int __cdecl CascDecrypt(unsigned char *,unsigned long *,unsigned char *,unsigned long,unsigned long)" (?CascDecrypt@@YAHPAEPAK0KK@Z) referenced in function "int __cdecl ProcessFileFrame(unsigned char *,unsigned long,unsigned char *,unsigned long,unsigned long)" (?ProcessFileFrame@@YAHPAEK0KK@Z)
    1>CascReadFile.obj : error LNK2019: unresolved external symbol "int __cdecl CascDirectCopy(unsigned char *,unsigned long *,unsigned char *,unsigned long)" (?CascDirectCopy@@YAHPAEPAK0K@Z) referenced in function "int __cdecl ProcessFileFrame(unsigned char *,unsigned long,unsigned char *,unsigned long,unsigned long)" (?ProcessFileFrame@@YAHPAEK0KK@Z)
    1>CascRootFile_Diablo3.obj : error LNK2019: unresolved external symbol "void * __cdecl Array_ItemAt(struct _DYNAMIC_ARRAY *,unsigned int)" (?Array_ItemAt@@YAPAXPAU_DYNAMIC_ARRAY@@I@Z) referenced in function "int __cdecl RootHandler_CreateDiablo3(struct _TCascStorage *,unsigned char *,unsigned long)" (?RootHandler_CreateDiablo3@@YAHPAU_TCascStorage@@PAEK@Z)
    1>CascRootFile_Diablo3.obj : error LNK2019: unresolved external symbol "unsigned int __cdecl Array_IndexOf(struct _DYNAMIC_ARRAY *,void const *)" (?Array_IndexOf@@YAIPAU_DYNAMIC_ARRAY@@PBX@Z) referenced in function "int __cdecl InsertFileEntry(struct TRootHandler_Diablo3 *,struct _ENCODING_KEY &,char const *,unsigned int)" (?InsertFileEntry@@YAHPAUTRootHandler_Diablo3@@AAU_ENCODING_KEY@@PBDI@Z)
    1>./bin/CascLib/Win32/DebugAD\CascLibDAD.dll : fatal error LNK1120: 8 unresolved externals
    ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Looks like overall what is missing is:

- Array_Create_
- Array_ItemAt
- Array_Insert
- Array_Free
- CascDecrypt
- CascDirectCopy
- Array_IndexOf
- InsertFileEntry

**Comment by ladislav-zezula** [comment]
Well, DLL project for VS2015 is not part of the repository, so you must have created it on your own. Add the missing files and it will be OK.
