### ISSUE TITLE
CascViewer: File Open dialog corrupted after multiple failed attempts to open

### ISSUE THREAD

**Issue by Luashine** [ladislav-zezula/CascLib#264]
Versions: 2.3.0.209 on Windows 7 & 2.4.0.298 on Windows 10 1607 (fresh VM install)
Release: 64-bit

After multiple failed attempts to "Open Storage" manually, CascView's FileOpen dialog will become broken and the program will not respond to attempts to close it or interact with anything. The FileOpen dialog will no longer have its window border and controls.

So far I could consistently replicate it on my machine after 7-8 tries:

1. Launch CASC Viewer
2. Click Open Storage
3. Give it any folder NOT containing data
4. Click away error message
5. go to 2
6. At some point Open File will become broken. One thread is blasting at 100%

![cascview-2 4 0 298](https://github.com/ladislav-zezula/CascLib/assets/103937213/831c9095-4f86-43dc-ba9a-70e1e353c30b)

Thread stack as shown by Process Explorer:
```
0x0000000000000000
win32u.dll!NtUserPeekMessage+0x14
USER32.dll!PeekMessageW+0xfe
USER32.dll!DialogBoxIndirectParamAorW+0x2d7
USER32.dll!DialogBoxIndirectParamAorW+0x1b3
USER32.dll!DialogBoxIndirectParamAorW+0x52
USER32.dll!DialogBoxIndirectParamW+0x18
COMDLG32.dll!GetFileTitleW+0x11f85
COMDLG32.dll!PrintDlgA+0x17a90
COMDLG32.dll!PrintDlgA+0x16594
COMDLG32.dll!PrintDlgA+0xfc66
COMDLG32.dll!Ssync_ANSI_UNICODE_Struct_For_WOW+0x3bc7
COMDLG32.dll!GetOpenFileNameW+0x70
CascView.exe+0x27c1
CascView.exe+0x71481
CascView.exe+0x7654b
CascView.exe+0x774f2
USER32.dll!CallWindowProcW+0x4f4
USER32.dll!CallWindowProcW+0x8b
UIRibbon.dll!DllMain+0x109157
atlthunk.dll+0x1026
USER32.dll!CallWindowProcW+0x4f4
USER32.dll!DispatchMessageW+0x1bc
USER32.dll!IsDialogMessageW+0x10f
CascView.exe+0x6adab
CascView.exe+0xd1612
KERNEL32.DLL!BaseThreadInitThunk+0x14
ntdll.dll!RtlUserThreadStart+0x21
```

**Comment by ladislav-zezula** [comment]
Hi, thanks for the bug report.

I can confirm the problem. However, it will take some time to fix it.
