### ISSUE TITLE
Misleading error message when .build.info not found

### ISSUE THREAD

**Issue by Luashine** [ladislav-zezula/CascLib#265]
CascView 2.4.0.298 x64 (CascLib v3.00)

> Error
> Incorrect format of the storage parameters
> Please, run CascView.exe /help to see the syntax of the command line.

CascView 2.3.0.209 (CascLib v2.00)

> Error
> Failed to open storage "C:\Users\MyName\Desktop\WarcraftBeta".
> The system cannot find the file specified.

In both cases ProcessMonitor shows that CascView cannot find the `.build.info`, because it was renamed. All I had to do to fix this is to 1) find out the reason 2) rename the file to its expected name.

**Expected:** CascViewer to report which required file was not found

**Actual:**

CascViewer starts at the target directory "C:\Users\MyName\Desktop\WarcraftBeta" trying to open these files:

1. `.build.info`
2. `.build.db`
3. `versions`

Failing that it recursively ascends directories and repeats the attempt until nothing is found at `C:/` level too. Then it stops (and presents the error message)

---

The 2.4.0 error message sounds like a failed CLI invocation. The 2.3.0 error message sounds like the folder could not be found and not that some files are missing.

**Comment by ladislav-zezula** [comment]
CascView is trying to open the storage in multiple ways. It is (sort-of) described in this page:
http://www.zezula.net/en/casc/main.html. 

I guess you figured the problem out, so it's solved :-)

**Comment by Luashine** [comment]
I solved my own problem but not as user-friendly as it could have been :) Close if you want.

**Comment by ladislav-zezula** [comment]
Fixed in PR: https://github.com/ladislav-zezula/CascLib/pull/266
Also, CascView shows a bit more descriptive error code on `ERROR_FILE_NOT_FOUND`. 

Until I upload the binary to my web, here it is:
[cascview_en.zip](https://github.com/ladislav-zezula/CascLib/files/13435909/cascview_en.zip)
