### ISSUE TITLE
warcraft rumble tech test support?

### ISSUE THREAD

**Issue by Joseffestan** [ladislav-zezula/CascLib#268]
Hello, are there plans to add support as Online for this: Warcraft Rumble Tech Test Development Region ?
The product code is gryphondev. 
thanks a lot!

**Comment by ladislav-zezula** [comment]
I tried, but the CDN config (1cb40c65054c676b04ee9f17c4040d83) is encrypted, so opening storage fails with "The file or directory is corrupted and unreadable".

**Comment by Joseffestan** [comment]
real pity. thank you anyway!
