### ISSUE TITLE
D2R: Failed to extract the file "data"locales\audio\eses\data\local\sfx\act1\warriv\war_act1_q4_early_scroll2.flac". The file is not present in the local storage.

### ISSUE THREAD

**Issue by Gbs498** [ladislav-zezula/CascLib#275]
Hi,

I am trying to extract D2R files using CascView. I am using the updated version from [here](http://www.zezula.net/en/casc/main.html). inside the data folder in D2R, there are 2 folders: Data and locales. I have extracted the Data folder without any issues. When I tried to extract the locales folder, I am getting the below error. 

D2R: Failed to extract the file "data"locales\audio\eses\data\local\sfx\act1\warriv\war_act1_q4_early_scroll2.flac". The file is not present in the local storage.

I have tried to skip the errors and continue extracting. Only 433 files were extracted out of 24007 files. 

I have not only reinstalled D2R multiple times, I have formatted by local Disk C and reinstalled Windows, then installed battle.net and Diablo 2 R. But still getting this issue after all this. I am trying to extract from CascViewer because I was trying to install few mods using D2RMM and after chatting with the volunteer in Nexus mods D2RMM page, he suggested I raise this issue here. Please do let me know if I need to share any logs. Can you help me how to resolve this issue?

**Comment by ladislav-zezula** [comment]
If the file is not present in the local storage, then it means that it's in the database files (such as ENCODING) but has not been downloaded yet.

Two things you may do:
- Let the Battle.net client fully download the game after install
- Let the Battle.net client repair the game

**Comment by Gbs498** [comment]
I do get prompts from battle net once in a while to update. Now I understand. Thanks
