### ISSUE TITLE
gryphon_vendor and gryphon_dev_3 support?

### ISSUE THREAD

**Issue by Joseffestan** [ladislav-zezula/CascLib#277]
Hello, there are two branchs of rumble today : gryphon_vendor and gryphon_dev_3. It would be so good if casc view can support those, thanks!

**Comment by ladislav-zezula** [comment]
I added it to CascView, but it doesn't seem to be available:

![image](https://github.com/user-attachments/assets/f0138c96-b8be-44a0-9932-d1911f7b0679)
