### ISSUE TITLE
Overwatch files inaccessible. 

### ISSUE THREAD

**Issue by Cohmervac** [ladislav-zezula/CascLib#28]
you can see in this screen shot. 
https://i.gyazo.com/b4677430911e2f0a89788ed9369b5c3d.png
They are totally inaccessible, and coincidentally they contain everything that actually matters.

**Comment by ladislav-zezula** [comment]
Not sure, where's the problem, but it works on my copy of CascView (1.0.0.39).
Moreover, if those files were inaccessible, the storage wouldn't be loaded at all.
