### ISSUE TITLE
I think the download needs to be updated...

### ISSUE THREAD

**Issue by Cohmervac** [ladislav-zezula/CascLib#29]
You said in a earlier issue that the folders in overwatch which are currently inaccessible (coincidentally the folders containing everything cool) are accessible to you, then you said a version number newer than that of the current download. I'm not sure if that's available through github, I don't know how to compile things or whatever. I'm sorry to bug you, but I'm just wondering, because I just really want to extract the models from the game for animations.

Sorry to bug you, I've just been checking every day since the game came out (I'm in beta) and I really really want to extract things. Also, happy thanksgiving!

**Comment by ladislav-zezula** [comment]
The version number of the webpage was not up to date, I fixed it.
The version on my webpage can open and load these four files from CASC storage.
