### ISSUE TITLE
2GB Unknown files in Storm of the heroes

### ISSUE THREAD

**Issue by kaikaiiiiiii** [ladislav-zezula/CascLib#35]
I extract that .xxx files. Some of them are text、xml、dds、ogg which can be recognized, others are totally known.

Is it a bug or I used in a wrong way?

Thanks.

**Comment by ladislav-zezula** [comment]
No idea.

Due to time reasons, I stopped doing any research regarding to MPQs and CASC. Especially on CASC, which is crappy format changing with every new Blizzard game, and sometimes even within game releases.
