### ISSUE TITLE
So you say it works... does that mean I'm using the wrong download?

### ISSUE THREAD

**Issue by Cohmervac** [ladislav-zezula/CascLib#37]
I've been trying to use this.
http://www.zezula.net/en/casc/main.html

And I get this result...
https://i.gyazo.com/8f5a734880191c90b71210bca80d1404.png
Everything but unknown is impossible to open, and has apparently no file type.
https://i.gyazo.com/0482caf1ff3cd124bcd20d148e90823a.png
Everything inside the unknown folder is also useless.
https://i.gyazo.com/8ebe38058bb82fccc1bae3457e138499.png

So am I using the wrong tool? Is that the wrong download? How do I get the one you say is working? I'm confused.

**Comment by ladislav-zezula** [comment]
The result you get is expected. I never figured out the format of CASC storage for Overwatch. So yes, most of the files are unknown.

**Comment by Cohmervac** [comment]
ah.

**Comment by WeirdMike** [comment]
@ladislav-zezula So does that mean that we won't be able to use CASC to view the Overwatch models?

**Comment by ladislav-zezula** [comment]
WeirdMike: Yes, it means you won't be able to use CASC to view Overwatch models.
