### ISSUE TITLE
Can't open latest D3 PTR build

### ISSUE THREAD

**Issue by d07RiV** [ladislav-zezula/CascLib#41]
I'm getting an error when opening the last PTR build in debug mode:

Assertion failed in `CascRootFile_Diablo3.cpp` line 621:

    assert(dwFileIndex < dwFileIndexes);

`dwFileIndex` and `dwFileIndexes` are both 451223.

**Comment by d07RiV** [comment]
It seems to work on my other installation, I'll have to investigate more closely when I get back to the first PC.

**Comment by d07RiV** [comment]
Okay, still encountering this problem after 2.4.1 release. I've attached my (root) and CoreTOC.dat files, I think these are the only files used up to that point?

[d3root.zip](https://github.com/ladislav-zezula/CascLib/files/239007/d3root.zip)

**Comment by ladislav-zezula** [comment]
Thanks. I'll look at it, eventually, but don't expect it any soon, I am quite busy these days.

**Comment by d07RiV** [comment]
Found the issue: https://github.com/ladislav-zezula/CascLib/pull/44

**Comment by ladislav-zezula** [comment]
I also rebuilt and uploaded CascView, so it should work now.
