### ISSUE TITLE
WoW Build 21737 and ulterior

### ISSUE THREAD

**Issue by Nelidon** [ladislav-zezula/CascLib#43]
Impossible to open a storage with CASC lib due to this error when opening Wow folder on Legion 21737+
Assertion failed: false, file F:\heimcore\core\dep\CascLib\src\CascOpenStorage.cpp, line 530

**Comment by ladislav-zezula** [comment]
Could you please lit me the entire directory <WoW>\Data\data? I'd like to see the sizes of *.idx files (and the others as well)

**Comment by Nelidon** [comment]
http://puu.sh/pbAus/2c718e2fc1.png
shmem = 12ko

**Comment by ladislav-zezula** [comment]
Fixed in commit 9b12536eaf8eb1b3e92f909de4b14602845a3a23.
CascView updated as well.
