### ISSUE TITLE
[WoW] Opening by FileDataId does not work as expected

### ISSUE THREAD

**Issue by Shauren** [ladislav-zezula/CascLib#45]
...In fact, it does not work at all.
After I modified `WowHandler_GetKey` to contain these lines
```
    if (pFileEntry)
        printf("%s - FileDataID %d\n", szFileName, pFileEntry->FileDataId);
```

Using sample code
```
    HANDLE CascStorage;
    CascOpenStorage(storage_dir.string().c_str(), CASC_LOCALE_ENUS, &CascStorage);
    HANDLE f;
    if (CascOpenFile(CascStorage, R"(World\Expansion04\Doodads\Pandaren\Stove\PA_stove_open_01.M2)", CASC_LOCALE_ENUS, 0, &f))
        CascCloseFile(f);
    if (CascOpenFile(CascStorage, "File00080A12", CASC_LOCALE_ENUS, 0, &f))
        CascCloseFile(f);
```

I get the following output
```
World\Expansion04\Doodads\Pandaren\Stove\PA_stove_open_01.M2 - FileDataID 147494982
```
with no entry for `File00080A12` - according to FileData.dbc the id of `World\Expansion04\Doodads\Pandaren\Stove\PA_stove_open_01.M2` is 526866 (00080A12 in hex), not 147494982

It looks like calculating FileDataId when opening the archive is doing something different than the wow client

Tested on fe97d8cf7fd2deb08db7e8c14990a6420a3b47b4, using both 6.2.4.21742 and 7.0.3.22248 clients (7.0.3 client had even different FileDataId for the file mentioned above)

This is even more important in 7.0.3 since FileData and FileDataComplete are both gone and files must be opened by their FileDataId.

**Comment by ladislav-zezula** [comment]
I was never able to fully figure out the FileDataID, that's probably why it doesn't work
I'll try to look at it, but don't expect it any soon - I no longer play WoW, I don't even have an installation of it.
