### ISSUE TITLE
Can't extract Nova: Covert Ops Maps

### ISSUE THREAD

**Issue by adrianbw** [ladislav-zezula/CascLib#49]
Whenever I try to extract these maps, I get error 6002. Is this fixable?

**Comment by ladislav-zezula** [comment]
No idea. I don't have the mission pack, nor I plan to buy it.

**Comment by adrianbw** [comment]
Alright, that's that, then! Thanks for making this, by the way—it's tremendously helpful.

**Comment by adrianbw** [comment]
...though it's likely the files are there even though you don't own the mission pack—they're all packed together now.

**Comment by ladislav-zezula** [comment]
Can you give me the path to the map file?

**Comment by adrianbw** [comment]
Here are the files I know can't be extracted:

SC2Data/mods/novastoryassets/base.sc2maps/maps/campaign/nova/nova01.sc2map
SC2Data/mods/novastoryassets/base.sc2maps/maps/campaign/nova/nova02.sc2map
SC2Data/mods/novastoryassets/base.sc2maps/maps/campaign/nova/nova03.sc2map
SC2Data/mods/novastoryassets/base.sc2maps/maps/campaign/nova/nstory01.sc2map
SC2Data/mods/novastoryassets/base2.sc2maps/maps/campaign/nova/nova04.sc2map
SC2Data/mods/novastoryassets/base2.sc2maps/maps/campaign/nova/nova05.sc2map
SC2Data/mods/novastoryassets/base2.sc2maps/maps/campaign/nova/nova06.sc2map

Thanks!

**Comment by ladislav-zezula** [comment]
I tried. First, it seems that "SC2Data/mods" is not a valid package name. When I tried to open it within "mods" package, it failed with "file not found".

Could you try to open this one:
mods/novastoryassets/base.sc2maps/maps/campaign/nova/nova01.sc2map

?

**Comment by adrianbw** [comment]
When I try to extract that file, I get Error code 6002 (0x00001772). Here's a gif that shows what happens:

![can t extract](https://cloud.githubusercontent.com/assets/12662580/17896919/e7fae466-6917-11e6-9e62-66798fda6f07.gif)

**Comment by ladislav-zezula** [comment]
Oh yeah, that lovely thing called cryptography.

 

Yes, I can confirm that the files are there already, but they are encrypted.

The key name is 0xd0cae11366ceea83 and it is now known yet.

See https://wowdev.wiki/CASC for the list of known keys

and watch for updates.

 

L.

**Comment by adrianbw** [comment]
Aha, thanks. Really appreciate you taking the time.
