### ISSUE TITLE
Failed to read archive due to read-only filesystem

### ISSUE THREAD

**Issue by Ralle** [ladislav-zezula/CascLib#51]
Hey guys,

I have been troubleshooting CascLib for a while now and only recently realized that my problem was that CascLib requires a read-write filesystem. I cannot use it when it does not have write permission to the SC2 files. Here is more information about the issue:

https://github.com/Kanma/CASCExtractor/issues/2

I understand CascLib may be able to add files at some point, but for a simple read operation, it shouldn't try opening files with write access.

**Comment by ladislav-zezula** [comment]
Fixed in commit 1d1f901ab49ac521190dad2a388c1047e5d8e65e.
CascView rebuilt as well.
