### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by theonlyShiro** [ladislav-zezula/CascLib#52]
Can anyone explain me how to compile CascLib? i dont know how to use VisulaStudio.

**Comment by theonlyShiro** [comment]
update  when i try to compile it with visualstudio 15. then gives me a error with CascLibRAD.lib cannot start and CascLibRAD.lib  is not a valid win 32- application

**Comment by Deaod** [comment]
You cant run CascLib on its own. Compiling in Visual Studio usually uses the Hotkey F7. Alternatively go to Build in the menu bar and click Build All.

**Comment by theonlyShiro** [comment]
can you explain me how extacly build and run CascLib im to stupid to make that thing works. i need a break @Deaod

**Comment by Deaod** [comment]
You cant run CascLib. If you want to actually extract files from games that use CASC, see here: http://zezula.net/en/casc/main.html

Compiling works as described. Open the .sln, acknowledge any upgrade, and hit F7.
