### ISSUE TITLE
How to use Casc Lib 

### ISSUE THREAD

**Issue by theonlyShiro** [ladislav-zezula/CascLib#53]
I have compiled Casc lib and i dont know what to do yet.
please explain it

**Comment by Lonswaya** [comment]
From your earlier ticket, he explained it already.


"You cant run CascLib. If you want to actually extract files from games that use CASC, see here: http://zezula.net/en/casc/main.html

Compiling works as described. Open the .sln, acknowledge any upgrade, and hit F7."

**Comment by Lonswaya** [comment]
Casc Lib is a Library, not a standalone program. The standalone program that uses it can be found in the link above.

**Comment by theonlyShiro** [comment]
@Lonswaya F7 dont work for my it absolutly nothing happens

**Comment by Lonswaya** [comment]
Because CascLib cannot be run like that. What are you even trying to do with this library?

**Comment by herrvigg** [comment]
hello,
to give a more precise answer @theonlyShiro : the CascLib core is a C library, not a ready-to-use program. So if you're not used to develop in C/C++ this might be quite difficult to use. If you just want to extract files then use CascView.

Still if you are motivated to learn and develop by yourself, you can start from the CascLib_Test project that creates an command-line exe (on windows). But even that requires a bit of experience in programming.

Another option is to start from another project above this library, for instance this one: https://github.com/nydus/storm-extract
The program can be run in command line with options. It references the CascLib as an external resource. However there is no VS project and not been tested under Windows, so in the current state you'll have to build it on Mac or Linux. It is certainly portable to Windows but it requires a bit of test and experience.
