### ISSUE TITLE
Error code 6002 on wow file ?

### ISSUE THREAD

**Issue by Jeromnimo** [ladislav-zezula/CascLib#55]
Hi, 

i get a strange issue with some files in WoW folder using casclib (within WoW Model Viewer). A user notified me that "AllianceMurloc" and HordeMurloc models are not displayed at all.

In a regular WoW install (7.1.0.22996), checking with code outputs, CascReadFile fails on these files : 
- creature\alliancemurloc\alliancemurloc.m2
- creature\hordemurloc\hordemurloc.m2

I got error 6002, which means "ERROR_FILE_ENCRYPTED" (according to https://msdn.microsoft.com/en-us/library/windows/desktop/ms681389(v=vs.85).aspx)

Do you have any idea from where this issue could come ?

Let me know if you need anything to investigate

**Comment by ladislav-zezula** [comment]
This error code means that the file is encrypted but the key is not
included in CascLib. CascLib is unable to decrypt the file.

**Comment by Jeromnimo** [comment]
Arf, ok, understand. And I suppose these keys are found using some reverse engineering or something similar.
wowhead site is able to display models corresponding to these files, I don't know if they are using casclib, but maybe you are in touch with them to get this key ? :)
Thanks for your quick answer

**Comment by Jeromnimo** [comment]
After some tries, I can already say that 
key is 0x8EE2CB82178C995A
both keys available in TactKey.db2 are not corresponding to this one unfortunatelly (if you want to add them in CascDecrypt.cpp, they are
{0x00, {0x43, 0x32, 0x65, 0xF0, 0xCD, 0xEB, 0x2F, 0x4E, 0x65, 0xC0, 0xEE, 0x70, 0x08, 0x71, 0x4D, 0x9E}},
{0x00, {0x1F, 0x8D, 0x46, 0x7F, 0x5D, 0x6D, 0x41, 0x1F, 0x8A, 0x54, 0x8B, 0x63, 0x29, 0xA5, 0x08, 0x7E}},

So I assume unfortunatelly, they are streamed from server :(

I have also checked against this page : https://wowdev.wiki/CASC#Key_CASC_Files but unfortunatelly this key is not referenced :(

Another potential "bug" (or at least unwanted behavior) in CascDecrypt, you are breaking FindCascKey search on keyname == 0, but you have some keys that are null, while other are not null after (so they are never searched for.

**Comment by ladislav-zezula** [comment]
Missing keys added in commit 9290202421cc55f23ec1ba3c264d607dba8d8791.
However, if we don't have the key for a file, there's no way to decrypt it.

**Comment by Jeromnimo** [comment]
I will check on irc if someone have the right key to read it and let you know if I get the right one so you can update casclib.

**Comment by Jeromnimo** [comment]
Page https://wowdev.wiki/CASC#Key_CASC_Files has just been updated and now contains a bunch of new keys, including the one I needed :)

**Comment by ladislav-zezula** [comment]
Added in commit e2fc95cdb15d03eb1e4c86b1161df82d5b92eff9. Please, try if it works for you.

**Comment by Jeromnimo** [comment]
I confirm it's working nicely :) Thanks for your quick support and prompt answer !
