### ISSUE TITLE
Expose FileDataId ?

### ISSUE THREAD

**Issue by Jeromnimo** [ladislav-zezula/CascLib#59]
Hi Ladislav, 

for WoW Model Viewer, I have just made an update in CascLib locally in order to expose a new function (CascGetFileId), because I needed it for my software.

Commit is here on my side if you want to look at it : https://bitbucket.org/wowmodelviewer/wowmodelviewer/commits/883670c46e2dfa4bea9a150deccaca263fac420d

Would you be interested in a pull request here to officialise it or do you think it is useless outside of my own need ?

**Comment by ladislav-zezula** [comment]
Well, if it's needed, then is is not useless :-)
Yes please, make a pull.

**Comment by sndwow** [comment]
FileDataId in the db2 file is very important, it is necessary this function.

**Comment by Jeromnimo** [comment]
I have created a pull request with needed changes.
I have left implementation empty for games other than WoW, as I don't know at all if FileDataId concept is applicable wider than WoW
