### ISSUE TITLE
Compilation failed with mingw and cmake

### ISSUE THREAD

**Issue by Jeromnimo** [ladislav-zezula/CascLib#6]
Hi Ladislav, 

just tried to compile casclib with mingw and cmake, and I needed to update CMakeLists.txt to suceed:
- add src/common/Map.cpp in SRC_FILES otherwise linker complies about missing Map_* functions
- remove  src/zlib/trees.c from ZLIB_BZIP2_FILES as this file is actually not part of repo

After that, everything goes well (not tried to use it yet, but compilation succeed)

I don't know which update method you prefer, do you want me to submit a patch, or do you prefer doing updates yourself ?

Regards.

**Comment by ladislav-zezula** [comment]
I'll do the fix and commit it.
