### ISSUE TITLE
Missing encryption keys

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#62]
[updateKeys.diff.txt](https://github.com/ladislav-zezula/CascLib/files/784807/updateKeys.diff.txt)

This is an update for some missing encryption keys. One of them is needed to view the new firecat mount.

This patch was made against the version of CascLib that we use in WoW Modelviewer but I believe it's up-to-date and so should work here as well.

**Comment by Jeromnimo** [comment]
Thanks Wain

Ladislav, I am currently preparing a pull request containing these changes, patch does not apply as is in CascLib (just tried this morning)

**Comment by Jeromnimo** [comment]
Pull request done :)
