### ISSUE TITLE
Mask seems to be ignored in CascFindFirstFile

### ISSUE THREAD

**Issue by herrvigg** [ladislav-zezula/CascLib#67]
hello,
i'm using CascLib directly for the first time, in Heroes of the Storm (25.0). 
I've just been running the test program which recompiles all the lib source files in its own exe. I adapted only the `main` to access the data source. The storage opens correctly, single files can be read, enumerate works, great !

But, if i try to change the mask in `CascFindFirstFile` nothing changes. It was `*` but if i change it for example to `*.xml` or anything else, it doesn't seem to have any effect, always returning all the files. Is that a bug or did i miss something and misunderstood this `szMask` parameter?

The lib is not documented so it's very hard to understand what is expected there, but i suppose it's a file token, accepting wildcards like "*" or "?" combined with filenames and/or path specification. I don't know if it handles a internal directory as well (i would expect it to return all the files in that directory).

Thanks for help.

**Comment by ladislav-zezula** [comment]
Commit a70abfa726b034374a7445f48a668a82fec1ebe2.
