### ISSUE TITLE
Crash when trying to open 7.3 folder

### ISSUE THREAD

**Issue by Jeromnimo** [ladislav-zezula/CascLib#76]
Hi Ladislav, 

currently evrybody is stuck with 7.3 WoW version (PTR), casclib ending up with a crash

Here is the crash stack 
0 "WowHandler_Insert" ( "d:\\development\\wowmodelviewer\\src\\casclib\\src\\cascrootfile_wow6.cpp" - 375 )
1 "InsertExtraFile" ( "d:\\development\\wowmodelviewer\\src\\casclib\\src\\cascopenstorage.cpp" - 234 )
2 "LoadRootFile" ( "d:\\development\\wowmodelviewer\\src\\casclib\\src\\cascopenstorage.cpp" - 927 )
3 "CascOpenStorage" ( "d:\\development\\wowmodelviewer\\src\\casclib\\src\\cascopenstorage.cpp" - 1075 )
4 "CASCFolder::setLocale" ( "d:\\development\\wowmodelviewer\\src\\games\\wow\\cascfolder.cpp" - 130 )

Before digging into it, if you have time, you will be more efficien than me :-)

**Comment by WainPetopia** [comment]
It looks like .build.info has changed in 7.3 and now has an extra row of values. The "header" section (containing variable names) seems to be the same between 7.2 and 7.3. The data rows seem to contain the same types of data but the keys have different values. One row begins with |0| and the other with |1|. In 7.2 I think there was just one row of data beginning with |1|. 

I don't know how the keys from the different rows are used.

**Comment by WainPetopia** [comment]
Update: on my Mac version the two rows contain different values. On my Windows version they don't. But my Windows version seems to be broken / corrupted so maybe the rows are supposed to have different keys.

**Comment by Jeromnimo** [comment]
In fact, even if you suppress inactive line (the one with "|0|") in it, crash occurs (on my installation they do contain different values).
Issue is really at initially stage in casclib, pbEncodingKey is invalid, causing a crash when we derefence it in cascrootfile_wow6.cpp, line 375.
That's why I asking Ladislav before digging into this issue myself

**Comment by ladislav-zezula** [comment]
I can confirm that the bug is there. I'll fix is ASAP.

 WainPetopia: Could you send me the .build.info from your mac, just to see?

**Comment by WainPetopia** [comment]
Thanks very much Ladik! I really appreciate it.

The build.info file from the PTR on my Mac is attached. I also play on Windows but that’s the one that became corrupted after a scan/repair. Blizzard still havent responded to that bug.

**Comment by ladislav-zezula** [comment]
Fixed in commit 16f80d1433525db73894b84d05af99e26847054d.

**Comment by WainPetopia** [comment]
Thanks so much!

Quick question: is there a repository for CascView where I can build a fixed version, or should I wait for you to update the one on the website? :)

Thanks again,

Wayne

**Comment by ladislav-zezula** [comment]
CascView updated as well. Sorry, I thought you just want the library :)

 

L.

**Comment by WainPetopia** [comment]
The library was important for WMV but I often use CascView for dataminign as well :)

Thanks again! We couldn’t operate without your tools.

**Comment by Jeromnimo** [comment]
Thanks for your reactivity Ladislav. I can confirm that issue is solved.
