### ISSUE TITLE
Support for SC1 remastered

### ISSUE THREAD

**Issue by LiquidWater** [ladislav-zezula/CascLib#78]
SCBW after 1.18 uses CASCs and MPQs for storing game files. Will there be CASClib support for SCBW in the future?

**Comment by ladislav-zezula** [comment]
If I get my hands on a game installation directory, maybe yes.

**Comment by LiquidWater** [comment]
The client should be free now, and an installer is available at https://us.battle.net/account/management/download/?show=classic

**Comment by ladislav-zezula** [comment]
That was easy. Support for Starcraft 1 added in commit b8a52c31443ad9130369f1ec8b02bc4e71d6c579.
CascView updated as well.

**Comment by LiquidWater** [comment]
Thanks
