### ISSUE TITLE
Broken build system: target "casc_static" which does not exist

### ISSUE THREAD

**Issue by doctaweeks** [ladislav-zezula/CascLib#90]
A bisect revealed 628ea3c989ae1c75d8eabfc99de7ebe88dd9124e introduced a bug that breaks the build system:
```
-- Compile dynamically linked library
CMake Error at CMakeLists.txt:135 (install):
  install TARGETS given target "casc_static" which does not exist in this
  directory.
```
Reproduce simply by running `cmake`.

An config option should not be used to determine whether an install target is even present in the build system.

**Comment by Jeromnimo** [comment]
@doctaweeks , thanks for raising the issue, your right, I have missed some basic tests here, my bad :/

Following your recommendation (on other threads), I will update it to use BUILD_SHARED_LIBS / BUILD_STATIC_LIBS for dynamic / static choice.

For install, I have to try, on WoW Model Viewer repo, but as I add CascLib as a subdirectory to compile it, my install target at WoW Model Viewer level cascades install in casclib

googling it a bit, it sounds EXCLUDE_FROM_ALL option of external_project can do the job, will look at it. If you have recommandation / examples, they are welcome :-)
